### ISSUE TITLE
Completeness of string indicating search parameters

### ISSUE THREAD

**Issue by agbeltran** [biocaddie/prototype_issues#10]
Steps:
1. search for 'egfr'
2. select 'GEMMA' repository
3. select 'organism' = mouse

The string at the top indicating the search parameters reads: "1-1 of 1 results for "egfr" in GEMMA" without mentioning the selection of the organism.

See screenshot.
![screen shot 2015-10-01 at 12 55 31](https://cloud.githubusercontent.com/assets/1417033/10220046/0fc5ffe0-683c-11e5-89a1-255fd6f09ebe.png)

**Comment by naturalbeau** [comment]
1.The UI now has a "clear all" button when any repository is selected, which allows user to deselect multiple repositories in one click.
2. In the detail view page, when user select any filter, the filter information will appear in the top of search results.

See screenshots.
![1](https://cloud.githubusercontent.com/assets/6586013/14297172/31892d1a-fb43-11e5-8407-7c10e65b0959.png)
![2](https://cloud.githubusercontent.com/assets/6586013/14297188/3ca4bc96-fb43-11e5-9259-4aa2e60db1fe.png)
