### ISSUE TITLE
"Download URL"

### ISSUE THREAD

**Issue by nursatranscriptomine** [biocaddie/prototype_issues#103]
The dataset metadata page for NURSA and ArrayExpress contains a field named "Download URL" that does not point to a download of the data, rather they are landing pages that contain download files, per FAIR principles.

I hope the screenshots below are visible, please e-mail me if not and I can send as attachments.

![image](https://cloud.githubusercontent.com/assets/14809879/15078941/4e608b36-137b-11e6-8119-4b6b3c318d80.png)

![image](https://cloud.githubusercontent.com/assets/14809879/15078981/834dcdae-137b-11e6-8313-6f2e2ca2565b.png)

**Comment by naturalbeau** [comment]
Hyperlink has been added to the download URL in arrayexpress. The Download URL is pointing to the dataset page in the original repository.
![1](https://cloud.githubusercontent.com/assets/6586013/15184531/2bca7472-175b-11e6-987a-5304179b6dd8.png)

**Comment by nursatranscriptomine** [comment]
The field name for NURSA Datasets (Download URL) is still incorrect - it points to the dataset landind page. The field name should be "Landing Page URL". Thx.

**Comment by naturalbeau** [comment]
Now the "Download URL" in NURSA has been changed to "Landing Page URL".
![2](https://cloud.githubusercontent.com/assets/6586013/15185473/fb14349a-175e-11e6-9795-6135649004d7.png)
