### ISSUE TITLE
Browse all the data for a particular repository

### ISSUE THREAD

**Issue by agbeltran** [biocaddie/prototype_issues#106]
I was assuming this link:

http://datamed.biocaddie.org/search-repository.php?query=%20&searchtype=data&repository=0003

was going to take me to the list of data from GEO, but there is nothing.
(I got to that link through the data repositories link: http://datamed.biocaddie.org/repository_list.php).
How can I see all the GEO data?
Thanks.

**Comment by naturalbeau** [comment]
Now the bug has been fixed. Please try it again.

**Comment by agbeltran** [comment]
Thank you.
