### ISSUE TITLE
Add what the fields are in Help

### ISSUE THREAD

**Issue by dianneusa** [biocaddie/prototype_issues#107]
Not sure what fields are being searched, can you list these in help with the allowed qualifier?

From help:
Search by Field

Terms may be qualified using bioCADDIE's search field tags.

The search field tag must follow the term -- you cannot prequalify.

Tags are enclosed in square brackets.

Example: Lung[title] AND Cancer

Reminders:

```
Boolean operators -- AND, OR, NOT -- must be entered in uppercase letters.
Boolean operators are processed from left to right.
Use parentheses to nest terms together so they will be processed as a unit and then incorporated into the overall strategy.
```

**Comment by RuilingLiu** [comment]
The help document has been updated.
