### ISSUE TITLE
LINCS:  datasets

### ISSUE THREAD

**Issue by chung88** [biocaddie/prototype_issues#109]
Can you send us a list of the LINCS dataset IDs?
http://datamed.biocaddie.org/search-repository.php?query=%20&searchtype=data&repository=0004

http://datamed.biocaddie.org/ shows 265 results and lincsportal has 264.

http://lincsportal.ccs.miami.edu/datasets/
{"results":{ "totalDocuments":264,

**Comment by naturalbeau** [comment]
After I looked into the lincs data in Datamed, I found there is an empty record in the Elasticsearch endpoint. I just deleted the empty item and now the LINCS has 264 results.
