### ISSUE TITLE
Broken link on landing page

### ISSUE THREAD

**Issue by RuilingLiu** [biocaddie/prototype_issues#110]
1. Enter "Heart Failure" in the search box on the landing page
2. Click on "dbGaP (13)" from the drop-down list
3. Error message: "datamed.biocaddie.org is currently unable to handle this request."

![screen shot 2016-06-13 at 10 20 44 am](https://cloud.githubusercontent.com/assets/11318005/16012770/8254d350-3150-11e6-87ad-0ed57653c668.png)

**Comment by naturalbeau** [comment]
The bug has been fixed.
