### ISSUE TITLE
"Send To" Feature Is Not Available On Safari

### ISSUE THREAD

**Issue by DataMedFeedback** [biocaddie/prototype_issues#114]
The "Send To" button does not display using Safari browser

**Comment by jgrethe** [comment]
I just demonstrated using Safari and I had the Send To button on the search results page...

**Comment by aegururaj** [comment]
The button pops-up as soon as at least one dataset is selected.

**Comment by saeid-p** [comment]
I will double check it with legacy versions of the Safari as well.

**Comment by saeid-p** [comment]
I checked with different versions of Safari. If user could provide me the version of Safari he/she is using, I can test it on that specific version. In general, it is suggested to use the latest version of the browser.

**Comment by saeid-p** [comment]
Currently, we decided to show "Send To" button by default. So it doesn't need to select a row to see this button. I close this issue for now as the problem can't be reproduced and the functionality will be changed soon.

**Comment by proccaserra** [comment]
Suggestion for adding a provisional category to 'Send to' function:

-send to 'analysis engine' (e.g. Galaxy or Knime) -> this would highlight a focus on reusability
