### ISSUE TITLE
Search result counts: Add "thousandths" place commas 

### ISSUE THREAD

**Issue by raprasad** [biocaddie/prototype_issues#116]
Minor formatting: e.g. "155,851" instead of "155851"

<img width="333" alt="datamed___biocaddie_ddi" src="https://cloud.githubusercontent.com/assets/1036060/16312508/ebb044ca-3929-11e6-8948-048e6bfb46a4.png">

**Comment by RuilingLiu** [comment]
"Thousandths" place commas have been added in version 1.0.

![datamed biocaddie ddi 2016-06-28 17-01-25](https://cloud.githubusercontent.com/assets/11318005/16433859/fc268b9e-3d51-11e6-950c-90412851c5b4.png)

**Comment by raprasad** [comment]
thanks @RuilingLiu
