### ISSUE TITLE
Indexing errors when exporting data to a file

### ISSUE THREAD

**Issue by RuilingLiu** [biocaddie/prototype_issues#118]
This issue is reported by Jason Smith from NIH.

He searched "Autism", selected three search results and exported the selected items to a file. 
The errors are in the attached text file.

[biocaddie-share (1).txt](https://github.com/biocaddie/prototype_issues/files/335597/biocaddie-share.1.txt)

**Comment by saeid-p** [comment]
I couldn't reproduce the error. However, there were some issues that I fixed and I think it may resolve this issue. @RuilingLiu can you provide me a link that can reproduce this error?

**Comment by RuilingLiu** [comment]
I just reproduced this bug.
1. Select these three search results below:
   [result 1](http://datamed.biocaddie.org/dev/biocaddie-ui/search-repository.php?query=Effectiveness+of+Atomoxetine+in+Treating+ADHD+Symptoms+in+Children+and+Adolescents+With+Autism&repository=0009&searchtype=data)
   [result 2](http://datamed.biocaddie.org/dev/biocaddie-ui/search-repository.php?query=Buspirone+in+the+Treatment+of+2-6+Year+Old+Children+With+Autistic+Disorder&repository=0009&searchtype=data) 
   [result 3](http://datamed.biocaddie.org/dev/biocaddie-ui/search-repository.php?query=Design+Of+WELL+Being+Monitoring+Systems%2C+Application+in+Autism&repository=0009&searchtype=data)
2. Click on "Send to" button and export the data to a file.

**Comment by saeid-p** [comment]
I found the bug caused this error. The problem has been resolved.
