### ISSUE TITLE
Too much information provided in description of dataset

### ISSUE THREAD

**Issue by RuilingLiu** [biocaddie/prototype_issues#13]
Often far too much information provided in description of dataset (e.g. phenotype information went on for >10000 words).

**Comment by saeid-p** [comment]
Hi @RuilingLiu. 

Thanks for the comment. Can you provide me a sample link and exact location of the description that needs attention?

Thanks

**Comment by saeid-p** [comment]
I checked all repositories description fields and fixed some with lengthy description. 
I close this issue at this moment. If we any other repositories needed more attention for the description field length, we can reopen it.
