### ISSUE TITLE
DataMed feedback

### ISSUE THREAD

**Issue by DataMedFeedback** [biocaddie/prototype_issues#131]
1. awesome!
2. How did I never know about BioProject?
3. on main page, not clear what X-axis is for the top 8 repositories- datapoints? datasets? other?

**Comment by RuilingLiu** [comment]
The value of x-axis is the number of datasets in each repositories

**Comment by ianfore** [comment]
Can we label the axis?

**Comment by tjohnson250** [comment]
Usability Severity Rating: 2 (Minor)
The x axis just needs to be labeled to resolve this issue.

**Comment by RuilingLiu** [comment]
A label has been add to x axis.

![screen shot 2016-08-22 at 11 14 33 am](https://cloud.githubusercontent.com/assets/11318005/17862154/a550e8a4-6859-11e6-84bb-5b7327c5605d.png)
