### ISSUE TITLE
[LINCS]:  data

### ISSUE THREAD

**Issue by chung88** [biocaddie/prototype_issues#137]
Summary:
-  datamed is showing 530 LINCS datasets, are twice the amount.

---

Note:  in the navigation LINCS (264)

---
1.  Go to http://datamed.biocaddie.org/repository_list.php, click on LINCS
2.  Displaying 20 of 530 results for " " in "LINCS" 20 Per Page 
3.  Switch view 
   Displaying 20 of 530 results for " " 20 Per Page 
   a)  (On item QA.3)  the search term is lost " "
   b)  The count 530 is two times 265.  In http://lincsportal.ccs.miami.edu/datasets/  Total Datasets: 264

---
1.  Search MCF7
2.  Select  LINCS (32)
3.  Displaying 20 of 32 results for " MCF7"
   a)  In http://lincsportal.ccs.miami.edu/datasets/    Search "MCF7"  Total Datasets: 31

---
1.  Search GCP
2.  Select LINCS (3)
3.  Displaying 6 of 6 results for "GCP" 
4.  Select all 6 items
5.  Click Send to:  File:  Submit
   See attachment:  .../367393/biocaddie-share.txt
   [biocaddie-share.txt](https://github.com/biocaddie/prototype_issues/files/367393/biocaddie-share.txt)
   a)  LDP "GCP"  Total Datasets: 3, not 6
   b)  The items in the UI and the items in the download file do not match.  Row 1 is "title": "BGJ398 KINOMEscan".  I do not believe it.  I re-start from scratch, steps 1 to 6.  The results are the same but the download is has three items, as indicated in the small Share Page Result icon number.
   [biocaddie-share (1).txt](https://github.com/biocaddie/prototype_issues/files/367395/biocaddie-share.1.txt)

---

Looking at the dataset blocks, in some I see cells names, proteins names under "name": , but the metadata across the same type of assays is not consistent.

---

The download URL between the UI and the download file does not match.
datamed UI download URL:    http://lincsportal.ccs.miami.edu/datasets/#/view/LDS-1265 
biocaddie-share.txt  "downloadURL": "https://panoramaweb.org/labkey/project/LINCS/GCP/begin.view?"

---

**Comment by jgrethe** [comment]
We checked the index on our side and it is half the size of what is returned by the UI.  Is the indexed doubled on production? Assigning to Ruiling to check on the datamed site.

**Comment by RuilingLiu** [comment]
**Question: datamed is showing 530 LINCS datasets, are twice the amount.**

Hi @chung88 , the DataMed website has been migrated to UCSD server. Please use https://datamed.org/index.php to explore the website.  

On the datamed.biocaddie.org website, we have two LINCS indexes, one is an old index, the other is an updated version from Jeff's team, we are trying to replace the old one with the updated one. We will remove the old one later.

Please try the steps below:
1. Go to https://datamed.org/repository_list.php, click on LINCS
2. Displaying 20 of 264 results for " " in "LINCS"

**Comment by RuilingLiu** [comment]
**Question: 
1. Search MCF7
2. Select LINCS (32)
3. Displaying 20 of 32 results for " MCF7" a) In http://lincsportal.ccs.miami.edu/datasets/ Search "MCF7" Total Datasets: 31**

The DataMed website uses terminology server to find synonyms of the query term. "MCF7" has the synonyms below:
1. MCF-7 Cell
2. Cells, MCF-7
3. Cells, MCF7
4. MCF 7 Cells
5. Michigan Cancer Foundation 7 Cells
6. Cell, MCF-7
7. Cell, MCF7
8. MCF7 Cells
9. MCF7 Cell

That's why DataMed returns more results than LINCS data portal.

**Comment by RuilingLiu** [comment]
**Question:
1. Search GCP
2. Select LINCS (3)
3. Displaying 6 of 6 results for "GCP"
4. Select all 6 items
5. Click Send to: File: Submit See attachment: .../367393/biocaddie-share.txt biocaddie-share.txt a) LDP "GCP" Total Datasets: 3, not 6 b) The items in the UI and the items in the download file do not match. Row 1 is "title": "BGJ398 KINOMEscan". I do not believe it. I re-start from scratch, steps 1 to 6. The results are the same but the download is has three items, as indicated in the small Share Page Result icon number. biocaddie-share (1).txt**

Please try these steps using https://datamed.org/index.php. You will get consistent results.

**Comment by chung88** [comment]
Yes, the search GCP returns only 3 records.

**Comment by RuilingLiu** [comment]
**Question:
The download URL between the UI and the download file does not match.
datamed UI download URL: http://lincsportal.ccs.miami.edu/datasets/#/view/LDS-1265 
biocaddie-share.txt "downloadURL": "https://panoramaweb.org/labkey/project/LINCS/GCP/begin.view?"**

This is a bug. @pournejati will take care of it. @chung88 Thank you for your feedback!

**Comment by RuilingLiu** [comment]
**Question:
Looking at the dataset blocks, in some I see cells names, proteins names under "name": , but the metadata across the same type of assays is not consistent.**

@chung88 Could you please send us some examples?

**Comment by saeid-p** [comment]
@RuilingLiu As we discussed, this should be fixed in the ElasticSearch side. 
The value in the metadata is not valid. We manually generate it on the interface side.

**Comment by RuilingLiu** [comment]
Hi @pournejati 

This dataset has download url in the [metadata](https://datamed.org/display-item.php?repository=0004&idName=ID&id=56d0fe04e4b0cd9ed8fc73c8&query=GCP%20data%20-%20kinase%20inhibitors). But when I download this dataset from the [search result page](https://datamed.org/search-repository.php?query=GCP%20data%20-%20kinase%20inhibitors&searchtype=data&repository=0004), there is no download url information in the biocaddie-share.txt file

Could you please double check the download function?

[biocaddie-share.txt](https://github.com/biocaddie/prototype_issues/files/439795/biocaddie-share.txt)

**Comment by RuilingLiu** [comment]
In the updated metadata, there is no download URL for this dataset
