### ISSUE TITLE
[LINCS}:  advanced search

### ISSUE THREAD

**Issue by chung88** [biocaddie/prototype_issues#138]
The following query is from the advance search:
 "Kinase"[All Search Fields] AND  "Proteomics"[All Search Fields]
[biocaddie-share.txt](https://github.com/biocaddie/prototype_issues/files/367406/biocaddie-share.txt)
Navigation count:
PDB (4);  Proteomexchange (3);  LINCS (2)
Displaying 11 of 11 results for ""kinase"[All Search Fields] AND "proteomics"[All Search Fields]"

a)  4+3+2 = 9;  Search shows:  11
b)  visual scan, two extra are from LINCS  4+3+4 = 11

I expected more results for proteomics + kinases.
The search kinase, returns very few LINCS results.

**Comment by RuilingLiu** [comment]
The query
"Kinase"[All Search Fields] AND  "Proteomics"[All Search Fields]
returns 29 results from the current [DataMed website](https://datamed.org/search.php?query=%22Kinase%22[All%20Search%20Fields]%20AND%20%20%22Proteomics%22[All%20Search%20Fields]&searchtype=data&offset=1).

![screen shot 2016-08-09 at 12 56 15 pm](https://cloud.githubusercontent.com/assets/11318005/17527389/ca9a4f5c-5e30-11e6-8192-53a22bfd6dae.png)

**Comment by RuilingLiu** [comment]
Hi @chung88 

I used "Kinase Proteomics" as a keyword and searched in [LINCS data portal](http://lincsportal.ccs.miami.edu/datasets/), there was no results found. Do you know any datasets related to "Kinase Proteomics" from LINCS, but has not been included in DataMed website?

Thanks!

**Comment by RuilingLiu** [comment]
Thank you for the feedback! We will reopen this issue if there are more questions later.
