### ISSUE TITLE
Feedback About Search Page

### ISSUE THREAD

**Issue by NinaSalimi** [biocaddie/prototype_issues#141]
Taken from #74 ----
This feedback has been collected from the survey form. In order to protect user's privacy, the personal information has been removed.

I am confused by the synonyms tag -- what does this mean? For example, when I searched "Canada" a synonym included was "Ginger, Wild" -- are these supposed to be like MeSH terms?

**Comment by soysal** [comment]
This was a terminology issue. Since countries were not in the terminology, Canada snakeroot (Asarum canadense or wild ginger - MeSH: D030023) was identified as the closest concept.

**Comment by naturalbeau** [comment]
We have added geographic regions to the terminology. Now the problem is fixed.

**Comment by naturalbeau** [comment]
Response has been sent to the user and no further reply received. Issue will be closed.
