### ISSUE TITLE
Polish instant search a bit more

### ISSUE THREAD

**Issue by Daniel-Mietchen** [biocaddie/prototype_issues#146]
I just went into DataMed and typed in "Aedes". This did not yield any results via instant search, even though there is a useful set of results after hitting the search button: 
https://datamed.org/search.php?query=aedes&searchtype=data .

**Comment by RuilingLiu** [comment]
Hi @Daniel-Mietchen ,

There are some results from protein structure, gene expression, clinical trials and unspecified data types. Is this the instant search you are talking about?

![capture](https://cloud.githubusercontent.com/assets/11318005/18418911/9983e806-780c-11e6-8a28-71612b9607ba.PNG)

**Comment by Daniel-Mietchen** [comment]
Yes, that's what I meant. I just checked again, and it worked fine. Could the reported issue be related to the slow WiFi here at the AHM?

**Comment by RuilingLiu** [comment]
@Daniel-Mietchen . It could be. It takes time to load the instant search results. Thank you for your feedback!

**Comment by NinaSalimi** [comment]
@Daniel-Mietchen , thanks for your feedback.
