### ISSUE TITLE
GWAS Dataset Finder not finding an expected GWAS

### ISSUE THREAD

**Issue by ianfore** [biocaddie/prototype_issues#157]
Searching the GWAS Dataset Finder for any of
Non-Hodgkins, Non hodgkin or Hodgkin does not return any results

There are known GWAS studies that look at Non-Hodgkin's Lymphoma.

Why does the GWAS Dataset Finder not find them?

**Comment by naturalbeau** [comment]
I have fixed the problem by changing the search fields to all fields. Before it just search some of the fields. Please take a look. @ianfore

**Comment by ianfore** [comment]
Thanks. It's now returning data.
We can close the issue but some bigger questions remain.
How do we decide which fields to search?
How do we drive that from what users would expect?
