### ISSUE TITLE
We need a label here in GitHub for version 1.5

### ISSUE THREAD

**Issue by ianfore** [biocaddie/prototype_issues#161]
Now Datamedbeta is available we need to be able to mark issues that we observe in that version.

**Comment by ianfore** [comment]
Thanks for the label!

**Comment by ianfore** [comment]
My error. I guess the label we need for tagging issues in datamedbeta at this point in time is v 1.5. Anything I've flagged so far as 2.0 is actually 1.5. Is it easy to just change the label? We probably don't need the 2.0 label yet.

**Comment by aegururaj** [comment]
The label has been changed to v1.5

**Comment by ianfore** [comment]
Thanks for the change
