### ISSUE TITLE
search result email error

### ISSUE THREAD

**Issue by soysal** [biocaddie/prototype_issues#167]
1. search for thyroid mass.
2. select 2nd and 9th result
3. Click send to
4. select email
5. enter your email
6. click submit.

You'll receive an email as:
bioCaddie data extracted for "thyroid mass".

Caught exception: Invalid argument supplied for foreach() Line: 58 Trace: #0 /var/www/biocaddie/Model/Repositories.php(58): {closure}(2, 'Invalid argumen...', '/var/www/biocad...', 58, Array) #1 /var/www/biocaddie/share.php(162): Repositories->__construct() #2 /var/www/biocaddie/share.php(156): shareSelective(Array, '
') #3 /var/www/biocaddie/share.php(54): shareEmailSelective(Array) #4 {main}

**Comment by RuilingLiu** [comment]
The bug has been fixed @soysal

**Comment by soysal** [comment]
verified.
