### ISSUE TITLE
Are repository requests going to the right GitHub repository?

### ISSUE THREAD

**Issue by DataMedFeedback** [biocaddie/prototype_issues#169]
Submitter's Name:test<br>Submitter Email:test@yahoo.com<br>Submitter's Organization:dfvdfb<br>Contact Person:gfgf<br>Contact Email:gfgh@dfgrg.com<br>Repository Full Name:fggf<br>Repository Abbreviation:dfdg<br>Repository Homepage URL:gfdgdfg.com<br>Repostitory Type of content:Protein Structure<br>Is a data use agreement required?:No<br>What dataset identifiers are used?:<br>Is metadata accessible in a machine-actionable format (XML, RDM, etc.)?:No<br>

**Comment by ianfore** [comment]
The data/request looks like is came from the repository entry form. Are those supposed to end up in the "prototype_issues" GitHub repository. Isn't there a repository specifically for managing repositories.

**Comment by naturalbeau** [comment]
It should go to the submit_repository-management issues. Have changed it. Please test it again. @ianfore

**Comment by ianfore** [comment]
Thanks for the fix. On the subject of retesting it..
Someone else did the test that resulted in it ending up here. I just happened to notice it here. I could work out how to do the test myself but I'd rather the original tester rechecked it. 
My goal is to ensure that testers are following through on the results of their testing. 
First, in checking through that the results of a test were as expected. 
Second, in reporting whether they were or not, and raising an issue where the results were not as expected
Third, following through on the fixes of anything that didn't work.

I know that those basics may or may not be absent in this case.

As an aside on good testing practice, imaginary data is dangerous. If the submitter had used their actual email address we'd be able to get back to them.

**Comment by ianfore** [comment]
Tested it myself. The entry went to the submit_repository-management issues repository
