### ISSUE TITLE
Non-Hodkgin GWAS search returns all records from many repositories

### ISSUE THREAD

**Issue by ianfore** [biocaddie/prototype_issues#180]
Search for dataset
search text "non-hodgkin gwas"

Returns (among other things) 560,261 protein structures.

The search seems to return the entire content of many repositories. See screenshot
Repository, % of repository returned by query
Swiss-Prot, 100%
ClinVar, 100%
ClinicalTrials.gov, almost 100%
BioProject, 100%
PDB, 100%
Dryad, ~75%
ArrayExpress, 100%
DataVerse, ~87%
NeuroMorph.org, 100%
etc.

![gwas](https://cloud.githubusercontent.com/assets/4731517/20848610/ce955ff0-b8a0-11e6-8987-f38d1b27dba4.jpg)

**Comment by jgrethe** [comment]
Looking at the search results - it may be related to the synonyms.  Looks like it is matching not just non-hodgkin lymphoma but also lymphoma and malignant as separate terms.

**Comment by ianfore** [comment]
Common words like "Non" might also cause problems.
However, a search for glioblastoma also returns the whole of SwissProt, ClinVar etc.
It's hard to see how a very specific and rare cancer can get expanded to return so many hits.

**Comment by naturalbeau** [comment]
The search algorithm has been changed. Please check it out.

**Comment by ianfore** [comment]
Thanks. This has addressed the problem that's matching everything.
