### ISSUE TITLE
Search for 5HT does not return expected results

### ISSUE THREAD

**Issue by ianfore** [biocaddie/prototype_issues#2]
**Steps taken**
Enter the search term 5HT and click go or press return/enter key

**Expected results**
See the attached screenshot which indicates two records which are in the index.
It would be reasonably expected that these would be returned in a search for the term 5HT as they contain 5HT in the title
![search1](https://cloud.githubusercontent.com/assets/4731517/9887764/4fdb1f4a-5bbf-11e5-9f2b-8b78b1eb6ec5.jpg)

**Results**
The second screenshot shows that the search does not return those results
![search2](https://cloud.githubusercontent.com/assets/4731517/9887767/5a50abf2-5bbf-11e5-91ef-4999cb228db6.jpg)

**Further Investigation**
Tried wildcarding the search as 5HT*. That did not change the results obtained.

Searching 5HT2C did bring back the one record that matched that. So it looks like the behavior is that the only match is for a whole word.

What behavior do users want?
How will users know how it works so they can query appropriately?

**Comment by naturalbeau** [comment]
The current search engine in the prototype does not handle wildcarding. Also, the search is operated on whole terms, so it does not do partial matching. That is why search "5HT" will not return "5HT2C".

**Comment by tjohnson250** [comment]
This is tricky, because if we do partial matching we'll possibly get many false positives. More intelligent query expansion and the advanced search may be better solutions.

**Comment by naturalbeau** [comment]
In the current version of datamed, we are not handling wildcarding. We will close this issue for now.
