### ISSUE TITLE
Boolean does not appear to work properly in searches

### ISSUE THREAD

**Issue by informationista** [biocaddie/prototype_issues#201]
I'm getting some weird numbers of search results when I use Boolean operators.  For example:
"colorectal cancer"[All Search Fields] OR  "CRC"[All Search Fields]: 337,566 results
"colorectal cancer"[All Search Fields]: 5,950 results
"CRC"[All Search Fields]: 500
Logically the maximum number of results I should get using OR between those two terms would be 5,950 + 500 = 6,450 but I got more than 50 times that amount.  

And even more confusing: 
"colorectal cancer"[All Search Fields] AND "CRC"[All Search Fields]: 337,531 results
If this were working properly the maximum number I should have returned is 500.

I tried a bunch of other combinations and got the same confusing results.  For example:
bronchitis: 119 results
asthma: 835 results
bronchitis AND asthma:  4,846 results
bronchitis OR asthma: 27,494 results

**Comment by naturalbeau** [comment]
The bugs have been fixed.

**Comment by naturalbeau** [comment]
@informationista The advanced search bug has been fixed. Could you please go to Datamed and check it out? Let us know if there is still any problem.

**Comment by informationista** [comment]
Yes, appears to be working now. Thanks!
