### ISSUE TITLE
Issue With Discrepancies between numbers of results in repositories

### ISSUE THREAD

**Issue by saeid-p** [biocaddie/prototype_issues#208]
Discrepancies between numbers of results in repositories and in DataMed is an issue. Need to
either synchronize well or explain to users.

A sample query run against GEO using the term “glucocorticoid receptor” produces a
different number of results than a query against GEO. Therefore, the reasons for these
inconsistencies needs to be addressed.

**Comment by saeid-p** [comment]
Updates to the GEO repository occurred after the ingestion process for DataMed was
completed. Further, we had an older incompletely ingested version of the GEO index for
DataMed v1.0. A quick search for the same term in DataMed v1.5 vs GEO provided 708
results in DataMed v1.5 and 508 in GEO [Entry types: DataSets(17), Series(203),
Samples(355) & Platforms(5)]. The increased results in DataMed v1.5 as compared to GEO
could be a result of synonym expansion in DataMed v1.5. Synonym expansion in GEO is
restricted only to MeSH terms while DataMed uses UMLS concepts to retrieve synonyms.

**Comment by aegururaj** [comment]
Duplicate of #202
