### ISSUE TITLE
Is there a way to highlight what the anchor points for the search were?

### ISSUE THREAD

**Issue by RuilingLiu** [biocaddie/prototype_issues#21]
Testing with “schizophrenia” as a search term and restricting to PDB – it’s not apparent how the first few results relate to schizophrenia from any of the details provided. Obviously schizophrenia-related sets appear ranked at around rank six or so. If this sort of thing is systemic it will be very confusing to users. Is there a way to highlight what the anchor points for the search were (e.g. where the term or its synonyms appear in the dataset index fields?)

![untitled](https://cloud.githubusercontent.com/assets/11318005/13499818/6e5d2954-e125-11e5-8f86-6eec7a96865d.png)

Issue reported by Dr. Trevor Cohen

**Comment by naturalbeau** [comment]
Now in the search result page, the search term will be highlighted.
![5](https://cloud.githubusercontent.com/assets/6586013/14440289/d26e31de-fff4-11e5-9107-34d6a1db660c.png)
