### ISSUE TITLE
Couple of issues with repositories.

### ISSUE THREAD

**Issue by saeid-p** [biocaddie/prototype_issues#211]
* In its current version, dataMED appears to have over 20 different data sources representing 65k
data sets and 10 different “data types”. This number is only a small fraction of the number of publicly
available databases as reported in the annual Nucleic Acids Research database issue (see next
paragraph).

* For example, although the link to data types appears to divide the results into some functional
categories, it is not clear that the choice of these categories is based on data definition standards
or ontologies. Therefore, a standard vocabulary and ontology-driven data model that fully captures
the scientific use cases should precede the development of a Data Discovery Index (DDI). Moved to #231

**Comment by saeid-p** [comment]
* We agree that the repository number is limited currently. While we are working to increase
DataMeds’ content, please do bear in mind that DataMed is currently a prototype and will not in its
present form encompass all data resources yet.

* We also have felt the requirement for a data type ontology. The bioCADDIE team has initiated
work in this area. We would like to clarify that the metadata model built by the bioCADDIE team is
based on various use cases (provided by multiple stakeholders) and encompassing existing
models in use by the community. Please see
https://biocaddie.org/group/working-group/working-group-3-descriptive-metadata-datasets for a
detailed description. The model is currently being refined based on feedback from the core
technology development team as it gets implemented for multiple repositories.

**Comment by saeid-p** [comment]
* If the meaningful use of data is the objective, why is the focus on a list of data sources rather than on
biological concepts? For example, should every user be familiar with GEO or Array Express or
GEMM or LNCS?#215 
* Why are only selected data sources provided? #216 
* There does not appear to be a categorization of these data sources that is intuitively useful. 
A new issue has been created for each of the above questions.

**Comment by saeid-p** [comment]
* Not every user is expected to be familiar with GEO, Array Express, etc. This is what DataMed is
meant to assist users with - letting them know what repositories (even if they are unknown to the
user) have potential data of interest.
* The repositories are prioritized for ingestion by DataMed on the basis of criteria defined by a working
group organized by bioCADDIE (for details, please check https://biocaddie.org/group/working-group/working-group-6-criteria-repository-inclusion-standards-interoperability). The group utilizes a priority score (developed and implemented by a working group in bioCADDIE: https://biocaddie.org/group/working-group/working-group-11-outreach-meeting-repository-operators) to decide the data sources that will be ingested.
* The data sources are currently classified based on the type(s) of data that are available from each of
them. We welcome any suggestion on better ways to organize the data resources.

**Comment by saeid-p** [comment]
### What is DataMed’s definition of a data type?
* bioCADDIE team members are currently working to develop a comprehensive data type ontology which
will provide definitions of types of data that should cover the breadth required for DataMed.
Moved to #217

**Comment by saeid-p** [comment]
### Although data types are shown, the underlying data model is not clear; for example, what is
the relationship between SRA, Phenotype, and Gene Expression?

* The data model can be found in the DATS documentation (https://biocaddie.org/group/working-group/working-group-3-descriptive-metadata-datasets)
Moved to #218

**Comment by saeid-p** [comment]
### Why are these considered different data types? Why are mouse phenome database and dbGAP under the same data type?

* Data type ontology is currently being worked as a refinement of DATS 2.1 and The various relationships
will be clear once the is generated.
Moved to #219

**Comment by NinaSalimi** [comment]
The issue has been addressed by bioCaddie team.
