### ISSUE TITLE
Suggestions on searching results and displays

### ISSUE THREAD

**Issue by saeid-p** [biocaddie/prototype_issues#212]
* The faceted search and presentation of results was helpful and will be even more helpful at guiding users to finding datasets when a larger number of repositories are included.
* Underlying data model and searching options were not clear: #218 
    * A list of types of search terms would be helpful.
    * **Suggestions:**
        * Include offering example queries.
        * An overview page that introduces the user to the resource and how one might use it.
More clearly stating the use case would also help.
        * If there are any publications related to this resource, providing them could also help
clarify the use cases and intended functionality for the user. #221

**Comment by saeid-p** [comment]
Thank you for the suggestions. We are currently also working on generating a detailed HELP and FAQ page. We hope that would be a useful resource for the user. The plan is also to add publications as they are generated.

**Comment by saeid-p** [comment]
* The ability to collect and manage results of interest via collections, sending to email, etc. is very nice. I also like the ability to save searches.
* Search facets come and go based on dataset. Probably a limitation of metadata, but it’s hard to
know that in advance.
* Minimal sorting options for results - should be able to go by date, as you can in systems
like arrayExpress. #222

**Comment by saeid-p** [comment]
Sorting by date functionality has been added in DataMed v1.5.

**Comment by saeid-p** [comment]
* Searching for gene symbols that match common English words (e.g. “BAD”) lead to mismatched
results. Some disambiguation is needed here - can matches to gene names or other specific
symbols be prioritized above generic text searches?
Moved to #223

**Comment by saeid-p** [comment]
We currently use NLP in conjunction with a terminology server to disambiguate and remove
common English words for the queries. We are working on including enhancements at the backend
(during ingestion and indexing) to complement this functionality.

**Comment by saeid-p** [comment]
* Auto-complete seems a bit unpredictable, and sometimes will strangely increase and decrease
number of matching results as keys are pressed.
Moved to #224

**Comment by saeid-p** [comment]
Autocomplete functionality has been removed for basic search due to formatting issues in IE. However, it is available for advanced search option. The results returned depends on the top term being suggested and we could see variation in the number of results being returned if the top term changes.

**Comment by saeid-p** [comment]
* When a simple query using “glucocorticoid receptor hypothalamus” was used, the results are not
aligned with the intent of the query. The screenshot below shows the results that are returned; do
these results represent datasets, publications and if they are indeed data sets, are they genomic,
clinical or other types of data? Furthermore, there is no mechanism by which the query can be refined
further. On the left hand side, although there are terms by which the query can be refined, such as
selection of gene expression, the results does not provide any guidance on whether the results
represent publications, data sources or whether there is a way to further analyze the results.
Moved to #225

**Comment by saeid-p** [comment]
All results returned by DataMed are datasets. DataMed does not index publications. We do provide
links to publications where possible. Also, where available, we provide annotations of type of data at
the level of the dataset. This information is unfortunately not provided by the repositories for every
dataset. Therefore, we are able to assign type of data at the repository level only. Information
integration of data analysis that is available for a dataset is being explored in a supplemental project
and may be integrated with later versions of DataMed.
General Usability

**Comment by NinaSalimi** [comment]
The first issue has been addressed by bioCaddie team.For each subsequent question, a new issue has been created.
