### ISSUE TITLE
General Usability Issues

### ISSUE THREAD

**Issue by saeid-p** [biocaddie/prototype_issues#213]
The links to the statistics were helpful and informative in all but one case:
* “4 pilot projects” does not appear to go anywhere, though there are 4 pilot projects listed at the bottom of the page. It’s not clear if that link is broken, or if it is intended to go into the field below. It is also not entirely clear how pilot projects are related to DataMed #233, and how one develops a pilot project if one is interested in doing so.

**Comment by saeid-p** [comment]
* Pilot project links have been restored in DataMed v1.5. Details about participation in pilot projects are available in the bioCADDIE website.

**Comment by saeid-p** [comment]
What do the numbers in the “top 8 repositories” refer to? Individual datasets? Something else? Not
clear.
Moved to #226

**Comment by saeid-p** [comment]
* DataMed v1.5 provides labels for this graph to indicate the top 8 repositories that are displayed in terms of maximum number of datasets in them.

**Comment by saeid-p** [comment]
I received the following confusing error code a few times: “Error: SimpleXML cannot create object”. This
is an example of poor error feedback, and offers no resolution. I don’t know if it’s something I did, or if
it’s a problem with the database itself. I don’t know if that means I’m missing results that should be
there, or what I should do about it.
Moved to #227

**Comment by saeid-p** [comment]
* This error issue was noticed internally as we used DataMed v1.0 and has been fixed in DataMed v1.5.

**Comment by saeid-p** [comment]
# Some Desired Functionality
* Reporting of broken links.
* Sorting results by other fields.
* Explanation of relevance.
* Alerts to new results from saved searches.
* Citation metrics and alerts for individual datasets, including links to publication.
Moved to #228

**Comment by NinaSalimi** [comment]
The issue has been addressed by bioCaddie team. For each subsequent question, a new issue was created.
