### ISSUE TITLE
The PDB link from the display of a specific dataset leads to the PDB interface, rather than to that dataset

### ISSUE THREAD

**Issue by RuilingLiu** [biocaddie/prototype_issues#22]
Same goes for ArrayExpress in another search.

Issue reported by Dr. Trevor Cohen

**Comment by jgrethe** [comment]
Do you mean that it goes to the PDB landing page for the dataset or the top-level PDB page?

**Comment by treversec** [comment]
To the top-level PDB page - which sort of makes sense, as it is the PDB icon, but I think a user that had followed the trial to our "individual dataset" page would be disappointed to have the trail from there lead to the need to search for the same set in PDB.

**Comment by RuilingLiu** [comment]
We removed the hyperlink from PDB icon.
The hyperlink of the title of a specific dataset will lead to that dataset in PDB.

We made the same change to other repositories.

![biocaddie data discovery index 2016-03-03 17-06-09](https://cloud.githubusercontent.com/assets/11318005/13512763/41459036-e162-11e5-8ae9-8ebd584d54d4.png)
