### ISSUE TITLE
Multiple Types

### ISSUE THREAD

**Issue by RuilingLiu** [biocaddie/prototype_issues#23]
Why is “Multiple Types” a data type, with fewer entries than e.g. Gene Expression?

Issue reported by Dr. Trevor Cohen

**Comment by naturalbeau** [comment]
"Multiple Types" means the repository contains different data types. We have changed the "Multiple Types" to "Unspecific" in the UI.

**Comment by treversec** [comment]
I'd suggest "Unspecified" (or "Nonspecific").

**Comment by naturalbeau** [comment]
Got it.
