### ISSUE TITLE
I’m here to inspire seniors all the way to healthier living

### ISSUE THREAD

**Issue by DataMedFeedback** [biocaddie/prototype_issues#234]
Hi!

Lately I’ve been devoting my focus to senior health — especially since only 28-34% of Americans aged 65-74 are physically active (http://www.fitness.gov/resource-center/facts-and-statistics/).

I’ve had the opportunity to speak with some of the elders in my community, and they said although they do want more physical activity, they feel limited in their options. Fortunately, inspiring others to get on their feet is my specialty! I’ve gathered some terrific resources on ways for seniors to lead happier, more active lives, but I need your help distributing them. What do you say — how about here: https://datamed.org/?

Transportation Options for Seniors Who Don’t Drive
https://www.neptunesociety.com/cremation-planning-for-caregivers/transportation-options-for-seniors-who-dont-drive

Outdoor Elderly Activities
http://www.elder-one-stop.com/outdoor-elderly-activities.html

Retiring in Your Own Home: How Baby Boomers Can Age in Place
http://www.homeadvisor.com/r/baby-boomers-aging-in-place/

The Healing Power of Pets for Elderly People
https://www.agingcare.com/articles/benefits-of-elderly-owning-pets-113294.htm

The Grandparent’s Guide to Sharing Your Love of Classic Cars with Your Grandchild
http://promotorsales.com/2016/10/18/the-grandparents-guide-to-sharing-your-love-of-classic-cars-with-your-grandchild/

Volunteer Abroad Programs for Senior Travelers
https://www.gooverseas.com/volunteer-abroad/seniors

The Senior’s Guide to Becoming a Real Estate Agent in Their Golden Years
https://www.redfin.com/blog/2016/03/the-seniors-guide-to-becoming-a-real-estate-agent-in-their-golden-years.html

Exercise Essentials for Healthy Aging
http://www.everydayhealth.com/senior-health/staying-active.aspx

Exercising with Osteoporosis: Stay Active the Safe Way
http://www.mayoclinic.org/diseases-conditions/osteoporosis/in-depth/osteoporosis/art-20044989

Here’s to happier senior living — because they truly are the golden years!

Thanks for your time,

Marie

Marie Villeza
http://elderimpact.org/ | elderimpact@gmail.com 
340 S Lemon Ave #5780 | Walnut, CA | 91789

If you’d prefer I didn’t reach out in the future, please send me an email letting me know. Thanks!

**Comment by ianfore** [comment]
See #274
