### ISSUE TITLE
"Similar Datasets" section does not show all results

### ISSUE THREAD

**Issue by yul129** [biocaddie/prototype_issues#239]
See the attached [screenshot](https://datamed.org/display-item.php?repository=0008&id=576adca4e4b0937a01a805de&query=PRJNA75875), some of the results are not shown up correctly, and when you click on the dots, they result in blank pages.
<img width="362" alt="screen shot 2017-01-25 at 1 50 08 pm" src="https://cloud.githubusercontent.com/assets/11788723/22310986/366e2c44-e306-11e6-8bed-9ff0ecaacd6c.png">

**Comment by RuilingLiu** [comment]
The bug has been fixed.

**Comment by NinaSalimi** [comment]
The issue has been addressed by bioCaddie team.

**Comment by NinaSalimi** [comment]
@yul129 thanks for your feedback. The issue has been resolved; please let us know if you have further questions.
