### ISSUE TITLE
Datamed website is not working

### ISSUE THREAD

**Issue by koweilin** [biocaddie/prototype_issues#242]
I received this e-mail from Dr. John S. Kaddis, City of Hope National Medical Center at 8:23 AM on Monday, Feb. 13, 2017. The website is working now. This is just for your team to keep the issue record.

From: Kaddis, John [JKaddis@coh.org]
Sent: Monday, February 13, 2017 8:23 AM
To: Lin, Ko-Wei
Subject: can you pass this message along?

 
https://datamed.org  website is not working.
 
Thank you Ko-Wei.
 
John
 
 
John S. Kaddis, Ph.D.
Assistant Professor
Department of Information Sciences
City of Hope National Medical Center
1500 East Duarte Road
Duarte, California 91010-3000
Office Phone: 626-218-3377
Fax: 626-301-8802
E-mail: jkaddis@coh.org
 
For meetings, schedules, and calendar items, contact:
Nelly Berger
Administrative Assistant
Phone: 626-218-1260
E-mail: nberger@coh.org

**Comment by aegururaj** [comment]
@koweilin, Thanks for logging the issue.
