### ISSUE TITLE
Search Result Interface Improvement Proposal

### ISSUE THREAD

**Issue by saeid-p** [biocaddie/prototype_issues#27]
This issue has been reported by Dr. Avi Ma’ayan (From the LINCS DCCIC).

The search results page is too cluttered. Here is the proposed rearrangement of the results page:
<img width="160" alt="biocaddie_mockup" src="https://cloud.githubusercontent.com/assets/6471104/13607020/fb456c68-e513-11e5-89a4-99cffc2b09f8.png">

**Comment by tjohnson250** [comment]
I suspect we need more feedback on this. Facets are almost always on the left, so I would not move them to the right. If you look at PubMed's results page they use more space for the results and have better page controls plus alignment of the results.

**Comment by NinaSalimi** [comment]
The page has been redesigned. An email was sent to Dr. Avi.
