### ISSUE TITLE
2 items- one big one little

### ISSUE THREAD

**Issue by DataMedFeedback** [biocaddie/prototype_issues#272]
Hello- first major feedback is that when i tried to access datamed I got an error- Your Connection Is Not Private and NET::ERR_CERT_DATE_INVALID.
I had to choose advanced options and "Proceed to datamed.org (unsafe)"
Second item is more minor- when I clicked in the box to search, there was no blinking cursor to give me feedback that it was ok to type.
Looking forward to playing with it some more!

**Comment by naturalbeau** [comment]
The problems have been fixed.
