### ISSUE TITLE
Seniors’ wellness resources for your review

### ISSUE THREAD

**Issue by DataMedFeedback** [biocaddie/prototype_issues#274]
Hi!

I just wanted to pass along some really wonderful health and wellness-focused resources for seniors. You already have such great information on your site on this topic (I love this page: https://datamed.org/) that I thought you may like to share a few more, so you are absolutely welcome (and encouraged!) to add these to your site. The page I mentioned above might be a good fit - what do you think?

Medication Safety For The Elderly: A Guide For Patients And Caregivers
https://www.pfizer.com/files/health/medicine_safety/4-6_Med_Safety_for_Elderly.pdf

Overdose Response Guide: Awareness, Prevention, And Preparedness For Caregivers Of Addicts
http://www.drugrehab.org/overdose-response-guide/

The Ultimate Guide To Senior Nutrition
https://www.mwhomecare.com/senior-nutrition-and-eating/

The Benefits Of Cooking With Alzheimer’s: A Caregiver’s Guide
http://www.culinaryschools.org/blog/cooking-with-alzheimers/

Health: What To Expect In Your 70s And Beyond
http://www.aarp.org/health/healthy-living/info-2017/over-70-healthy-living-tips.html

A Guide To Downsizing For Seniors And Their Loved Ones
https://www.redfin.com/blog/seniors-guide-to-downsizing

Is My Elderly Parent Incompetent? What To Do If You’re Worried
http://betterhealthwhileaging.net/qa-possible-elderly-incompetence-what-you-can-do/

Senior-Friendly Remodeling
http://www.homeadvisor.com/r/senior-friendly-remodeling/

12 Ways To Help Seniors Avoid Social Isolation
http://samvednacare.com/blog/2016/04/27/12-ways-to-help-seniors-avoid-social-isolation/

Caretakers’ Guide To Moving Seniors Into A Facility
https://www.closetbox.com/resources/caretakers-guide-to-moving-seniors/

Thanks for all you do to promote senior health! If we can do more to help your cause - perhaps by writing a blog-style post for you to share - please let us know. Or, if you don’t want to participate in our outreach anymore, please email us with “unsubscribe” in the subject line.

Many thanks in advance!

Thank you,
Marie

Marie Villeza
elderimpact@gmail.com

**Comment by ianfore** [comment]
I agree this should be closed. See response below sent to Marie who posted the feedback.
Ian

Dear Marie,

Many thanks for the feedback you provided a while back via the feedback form provided on Datamed.org.

The development team reviewed the feedback as to whether it is something they could address as part of the system. Datamed is intended as a way of finding datasets- typically results data from scientific investigations, studies and clinical trials. There are certainly datasets listed in DataMed which address senior health issues. However, the resources listed are informational resources which would likely be better listed in other places.

The resources you listed are certainly valuable for seniors. The various institutes within NIH provide information of this kind to the public via various routes. In some cases the information is produced directly by NIH, in other cases it is from third parties. A relevant example is the listing of health information provided by the National Institute on Aging (NIA).
https://www.nia.nih.gov/health

If you wish to follow up further I would suggest contacting the NIA directly at the link provided on the page above. 

Best regards
Ian Fore


Ian Fore, D.Phil.
Senior Biomedical Informatics Program Manager
NCI Center for Biomedical Informatics and Information Technology


_______________________________________
Seniors’ wellness resources for your review

Hi!
I just wanted to pass along some really wonderful health and wellness-focused resources for seniors. You already have such great information on your site on this topic (I love this page: https://datamed.org/) that I thought you may like to share a few more, so you are absolutely welcome (and encouraged!) to add these to your site. The page I mentioned above might be a good fit - what do you think?
Medication Safety For The Elderly: A Guide For Patients And Caregivers
https://www.pfizer.com/files/health/medicine_safety/4-6_Med_Safety_for_Elderly.pdf
Overdose Response Guide: Awareness, Prevention, And Preparedness For Caregivers Of Addicts
http://www.drugrehab.org/overdose-response-guide/
The Ultimate Guide To Senior Nutrition
https://www.mwhomecare.com/senior-nutrition-and-eating/
The Benefits Of Cooking With Alzheimer’s: A Caregiver’s Guide
http://www.culinaryschools.org/blog/cooking-with-alzheimers/
Health: What To Expect In Your 70s And Beyond
http://www.aarp.org/health/healthy-living/info-2017/over-70-healthy-living-tips.html
A Guide To Downsizing For Seniors And Their Loved Ones
https://www.redfin.com/blog/seniors-guide-to-downsizing
Is My Elderly Parent Incompetent? What To Do If You’re Worried
http://betterhealthwhileaging.net/qa-possible-elderly-incompetence-what-you-can-do/
Senior-Friendly Remodeling
http://www.homeadvisor.com/r/senior-friendly-remodeling/
12 Ways To Help Seniors Avoid Social Isolation
http://samvednacare.com/blog/2016/04/27/12-ways-to-help-seniors-avoid-social-isolation/
Caretakers’ Guide To Moving Seniors Into A Facility
https://www.closetbox.com/resources/caretakers-guide-to-moving-seniors/
Thanks for all you do to promote senior health! If we can do more to help your cause - perhaps by writing a blog-style post for you to share - please let us know. Or, if you don’t want to participate in our outreach anymore, please email us with “unsubscribe” in the subject line.
Many thanks in advance!
Thank you,
Marie
Marie Villeza
elderimpact@gmail.com
