### ISSUE TITLE
Some URLs in sitemap files are invalid

### ISSUE THREAD

**Issue by ianfore** [biocaddie/prototype_issues#280]
The following URL is contained in the sitemap10.xml file. It does not return a dataset page - though it seems it is trying to return an ICPSR entry
https://datamed.org/dataset/0025/580e9ff25152c648c68ceecc/-Capital-Punishment-in-the-United-States%2C-1973-2004

The same problem occurs for this one
https://datamed.org/dataset/0025/580ea00b5152c648c68cf4bd/-General-Social-Survey%2C-1976

This example, from another file, works
https://datamed.org/dataset/0044/5841d91c5152c649505fbf0c/Transcription-profiling-of-human-adult-to-adult-living-donor-liver-grafts-compared-to-deceased-donor-grafts
It comes from a different repository. 

It's possible that it's just the ICPSR entries that are a problem - but it looks like a thorough check of the problem is necessary.

**Comment by ianfore** [comment]
For the first URL this is presumably the page that is intended
https://datamed.org/display-item.php?repository=0025&id=58f02e815152c60f611950c8

I suspect what's happened is the the id of the dataset has changed since sitemap file was generated. The id is part of the URL. If you fix the id the form of the URL used in the sitemap does work. 
https://datamed.org/dataset/0025/58f02e815152c60f611950c8/-Capital-Punishment-in-the-United-States%2C-1973-2004

The issue here then is the question of when the sitemap files are created/updated.

**Comment by ianfore** [comment]
Encountering other examples of the problem e.g. this one from https://datamed.org/sitemap2.xml

https://datamed.org/dataset/0006/581146df5152c6582af38938/Identification-and-molecular-characterization-of-distinct-glioblastoma-cancer-stem-cell-populations

**Comment by JingAn2017** [comment]
@ianfore The sitemap files are updated, please check. Thank you.

**Comment by JingAn2017** [comment]
Please feel free to contact me if any questions.
Thank you.
