### ISSUE TITLE
HTML is being parsed/displayed incorrectly in title

### ISSUE THREAD

**Issue by jmcmurry** [biocaddie/prototype_issues#287]
https://datamed.org/search-repository.php?query=%20&searchtype=data&repository=0010

<img width="562" alt="screen shot 2017-08-07 at 12 16 31 pm" src="https://user-images.githubusercontent.com/3658863/29042116-81310aa6-7b6a-11e7-8e62-43d6d409a40a.png">

**Comment by yul129** [comment]
Neither raw data or the transformed data has these HTML characters.

**Comment by jgrethe** [comment]
Looks like something in the HTML rendering on the UI is making these links text - rather than a link on the page...

**Comment by jmcmurry** [comment]
yes

**Comment by JingAn2017** [comment]
Please test.

**Comment by jmcmurry** [comment]
It is not fixed yet. Please try the link locally first. https://datamed.org/search-repository.php?query=%20&searchtype=data&repository=0010

**Comment by JingAn2017** [comment]
Have deployed the code to datamed beta server. 
May be later Anu will send you the link. Thank you.

**Comment by jmcmurry** [comment]
it appears fixed on beta

**Comment by aegururaj** [comment]
Thanks for testing, Julie

**Comment by JingAn2017** [comment]
The production server is updated.  https://datamed.org/search-repository.php?query=%20&searchtype=data&repository=0010
