### ISSUE TITLE
Change The Banner Logo

### ISSUE THREAD

**Issue by saeid-p** [biocaddie/prototype_issues#29]
This issue has been reported by Dr. Avi Ma’ayan (From the LINCS DCCIC).

Not a fan of the banner text. TeXt sEEms tO LooK liKE tHIs Too MUch.

**Comment by tjohnson250** [comment]
This is true, but I never noticed it until now. I would rate this at 1: Cosmetic

**Comment by NinaSalimi** [comment]
An email was sent to the reporter notifying him that the logo is coming from the BioCaddie website and that we do not have any control over it.
