### ISSUE TITLE
Analitica Latin America 

### ISSUE THREAD

**Issue by DataMedFeedback** [biocaddie/prototype_issues#290]
Hi, 

Wishing you all the best for Analitica Latin America 2017 !!!

Would you be interested in reaching out to Presidents, Vice Presidents, Partners, Owners, Directors, Managers, Technicians, Consultant Experts, Engineers, Coordinators, Supervisors and much more? for your Email campaign, Tele-marketing and other marketing initiatives from the following sectors,

•        Academic / Scientific
•        Food Industry
•        Environmental
•        Biotechnology
•        Cosmetics
•        Distribution
•        Energy
•        Entity / Government
•        Pharmaceutical Industry
•        Laboratory
•        Logistics
•        Machines and Equipment
•        Raw Material
•        Petrochemicals
•        Analytical Chemistry
•        Health
•        Services
•        Paints

We can get you a list of prospective clients and customers with their company name, contact name, job title, phone number, e-mail addresses and much more information as per your requirement across US/UK/CANADA/Australia, Europe and from across the world.

Please fill in the information in the below format and I’ll revert with the data benefits, counts and cost for your review:

Target Industries/Sectors   :  _____?
Target Locations                   :  _____?
Target Job Functions            :  _____?

Looking forward to your early response.

Best Regards,
Jennifer Young
Senior Database Consultant

**Comment by ianfore** [comment]
Spam.
