### ISSUE TITLE
Transformation validation error for the metadata with deep layers in a nested structure

### ISSUE THREAD

**Issue by zongnansu1982** [biocaddie/prototype_issues#293]
[EXR-JFREE1eZDUKB-AN_json.txt](https://github.com/biocaddie/prototype_issues/files/1315054/EXR-JFREE1eZDUKB-AN_json.txt)

One issue of transformation validation was found for ExRNA. When there are too many layers in a nested structure, the script seems cannot handle it well.  A sample data is attached and a sample script is shown as, 

transform column "$.'samples'[*].'Biosample'.'properties'.'Biological Sample Elements'.'properties'.'Biological Fluid'.'properties'.'Collection Details'.'properties'.'Sample Collection Method'.'value'" to "activity.name";

transform column "$.'samples'[*].'Biosample'.'properties'.'Biological Sample Elements'.'properties'.'Biological Fluid'.'properties'.'Collection Details'.'properties'.'Collection Tube Type'.'value'" to "activity.extraProperties[0].value";

transform column "$.'samples'[*].'Biosample'.'properties'.'Biological Sample Elements'.'properties'.'Biological Fluid'.'properties'.'Collection Details'.'properties'.'Collection Tube Type'.'value'" to "activity.extraProperties[0].category" apply {{ result = 'Collection Tube Type}};

**Comment by bozyurt** [comment]
There was a syntax error missing closing single quote after 'Collection Tube Type' in the apply section. The corrected rule below works. You can test one or more rules using the web service at http://52.34.32.154/foundry/#/transform with API key 768022a9e4a37fd3d4006842ad72e159

transform column "$.'samples'[*].'Biosample'.'properties'.'Biological Sample Elements'.'properties'.'Biological Fluid'.'properties'.'Collection Details'.'properties'.'Collection Tube Type'.'value'" to "activity.extraProperties[0].category" apply {{ result = 'Collection Tube Type' }};

Burak
