### ISSUE TITLE
Agent for Datamed in Qatar

### ISSUE THREAD

**Issue by DataMedFeedback** [biocaddie/prototype_issues#294]
Dear Sir,

Allow the opportunity to introduce Solutions for Services and Healthcare W.L.L . Solutions is company established in 2011 under the state of Qatar. We have built bridges of partnership with renowned international partners such as GE HEALTHCARE, OLYMPUS,KLS MARTIN, METRO, ZOLL , ENRAF NONIUS, SARSTEDT and more. Solutions pride itself not only by  building  its reputation by representing well renowned international companies , but by building local sales and service expertise to get closer to our customers who  determined our success.

Moving forward we will be very much interested in exploring the possibility of a partnership  between DataMed®  and SSH. We truly believe that our partnership will be both fruitful and Beneficial between both companies. 

We will be available at your entire convenience to discuss the market potential and opportunities. 

With Best regards,

sHamzeh Gheidan
Key Account Manager 

SOLUTIONS FOR SERVICES AND HEALTHCARE W.L.L
P.O. Box. No.  201285, Doha – Qatar
T + 974 4436 0323
M + 974 5066 8880
Fax + 974 4421 7008
E mail: Hamzeh.Gheidan@sshqatar.com
www.sshqatar.com

**Comment by aegururaj** [comment]
Solicitation email
