### ISSUE TITLE
Searching for pmid:9405351 does not find the relevant data in the index

### ISSUE THREAD

**Issue by ianfore** [biocaddie/prototype_issues#3]
**Steps taken**
Enter the the text pmid:9405351 into the query field and run it. 

** Results **
No results are obtained

Searching by 9405351 does not return anything either.

**Expected results**
The thought behind this query is 
"what are the data related to the publication identified in pubmed as 940535?"
There is certainly PDB data in the index which correspond to that.

These records can be found using this search term in elasticsearch directly. However, the user interface is not finding it.

**Comment by RuilingLiu** [comment]
Using PMID as one of the search fields. Now searching for pmid:9405351 will return the relevant data in the index.

<img width="1240" alt="screen shot 2016-04-07 at 4 34 16 pm" src="https://cloud.githubusercontent.com/assets/11318005/14367620/9c46f1a4-fcde-11e5-8840-d719ec3c55b1.png">
