### ISSUE TITLE
Licence to publish your logo in our Nature Ecology & Evolution Paper

### ISSUE THREAD

**Issue by DataMedFeedback** [biocaddie/prototype_issues#304]
Dear DataMed,

We have a paper accepted in the Nature Ecology & Evolution. In one of our figures we used your logo (amongs other logos, such as EUDAT, OpenAIRE, or DataCite). 

In order to publish our paper (and as soon as possible) we would need to obtain the licence to do so.  Could you please provide me with a contact (email) where I can send the Licence to Publish form, and the Figure in question.

We appreciate your prompt response
Very best
Antica Culina, on behalf of all of the authors

**Comment by jgrethe** [comment]
HI Antica,
Elizabeth Bell ( @eabell ) should be able to help you with that.

**Comment by aegururaj** [comment]
Thanks, Jeff. I did get in touch with Antica and she has sent the form in which I've forwarded to Elizabeth.

**Comment by aegururaj** [comment]
completed @eabell
