### ISSUE TITLE
Links under Top 7 Datasets on homepage

### ISSUE THREAD

**Issue by DataMedFeedback** [biocaddie/prototype_issues#306]
https://datamed.org/index.php

If I click on any of the links under "Top 7 Datasets" I am prompted for a username and password. I think this has something to do with linking to datamedbeta.biocaddie.org instead of datamed.biocaddie.org.

I assume this (i.e. access restrictions a single click from the hompage) is not intended. 

Thanks for the site,

Mike

**Comment by JingAn2017** [comment]
Fixed the issue and sent below email to user.
Dear User,

Thank you for bringing it to our attention!
The issue is fixed.
Could you please check it again?
Thank you.

Best Regards,
bioCADDIE

**Comment by mrueschman** [comment]
The links are now working as expected. Thanks!
