### ISSUE TITLE
advanced search fields question--GrantName

### ISSUE THREAD

**Issue by DataMedFeedback** [biocaddie/prototype_issues#310]
Hi,
I am hoping you can tell me the best way to search for datasets associated with a list of grant numbers. I have experimented with your advanced search field--grantname but when I input P42 receive no results. I can pull up datasets related to NIEHS using the organization field--NIEHS but I would like to search for datasets associated with specific grant numbers. Thank you!

**Comment by JingAn2017** [comment]
Added grant id to advanced search and sent below email:
Dear Lesley,
Sorry for reply late.
We added the filed: "grant id" to advanced search.
Hope this helps.
Thank you for your support.
Regards,
bioCADDIE
