### ISSUE TITLE
Organization field in advanced

### ISSUE THREAD

**Issue by DataMedFeedback** [biocaddie/prototype_issues#311]
Do all the repositories included in dataMed use an Organization field?  I did a few searches and barely received any results and I am wondering why.

**Comment by JingAn2017** [comment]
Sent below email:

Dear Melissa,

Some repositories don't use an Organization field, so the datasets of the repositories won't appear in the results.
The search filed is Organization Name. 
Hope this helps.

Regards,
bioCADDIE
