### ISSUE TITLE
Do you accept guest article submissions?

### ISSUE THREAD

**Issue by DataMedFeedback** [biocaddie/prototype_issues#326]
Hello!

Entering recovery is a wonderful and life-changing experience. But, unfortunately, doing so doesn’t mean all other aspects of one’s life fall into place overnight. 

For example, getting a job can be especially difficult and intimidating. I understand the stress associated with looking for that first job out of rehab because I experienced it myself. 

I’d like to help by offering tips to those new to recovery on how to get their career back on track after rehab, whether they’re entering the job market or starting their own business. I could put this information in an article for your website. Would that be ok?

Thank you for taking a look!
Rufus 

Rufus Carter | rufus@recoveringworks.com
RECOVERINGWORKS.COM

**Comment by aegururaj** [comment]
Spam
