### ISSUE TITLE
Unnecessary Suggestion Panel In The Landing Page While Searching

### ISSUE THREAD

**Issue by saeid-p** [biocaddie/prototype_issues#33]
This issue has been reported by Dr. Avi Ma’ayan (From the LINCS DCCIC).

That dropdown that opens when you start searching is a little confusing and a bit annoying. Let the user filter results once the search is complete.

**Comment by margolisr** [comment]
This is a valid comment that relates to ease of use of the search feature of the UI. It is imperative to have a 'clean' entry to the UI to allow for both ease of use (both experienced and naïve user) and rapid return of results. Filters that are simple to apply will make the process smooth and encourage return use.
