### ISSUE TITLE
Query

### ISSUE THREAD

**Issue by DataMedFeedback** [biocaddie/prototype_issues#356]
Hi,

Hope you are doing well. I just wanted to know if i could send some great article ideas for a guest post on your website.

If you like the ideas i put forward, i will provide you with high-quality free content/articles. In exchange, all i expect is a back link from within the main body of the article.

Do let me know if you like this proposal and if i can begin sending you some topic ideas.

Best Regards

Ashlie Lopez

**Comment by aegururaj** [comment]
Spam
