### ISSUE TITLE
You deserve more clients for datamed.org and it’s THIS easy

### ISSUE THREAD

**Issue by DataMedFeedback** [biocaddie/prototype_issues#357]
Hello,

You know it’s true.

Your competition just can’t hold a candle to the way you DELIVER real solutions to your customers at datamed.org

But it’s a shame when good people who need what you have to offer wind up settling for second best or even worse.
  
Not only do they deserve better, you deserve to be at the top of their list.
 
TalkWithCustomer can reliably turn your website into a serious, lead generating machine.
 
With TalkWithCustomer installed on your site, visitors can either call you immediately or schedule a call for you in the future.
  
And the difference to your business can be staggering – up to 100X more leads could be yours, just by giving TalkWithCustomer a FREE 14 Day Test Drive.
 
There’s absolutely NO risk to you, so CLICK HERE http://www.talkwithcustomer.com to sign up for this free test drive now. 
 
Tons more leads? You deserve it.

Sincerely,
Andy

PS:  Odds are, you won’t have long to wait before seeing results:
-This service makes an immediate difference in getting people on the phone right away before they have a chance to turn around and surf off to a competitor’s website.- David Traylor, Traylor Law Firm
  
Why wait any longer?  

CLICK HERE http://www.talkwithcustomer.com to take the FREE 14-Day Test Drive and start converting up to 100X more leads today!

If you'd like to unsubscribe click here. http://liveserveronline.com/talkwithcustomer.aspx?d=datamed.org

**Comment by aegururaj** [comment]
Spam
