### ISSUE TITLE
Home page logos

### ISSUE THREAD

**Issue by RuilingLiu** [biocaddie/prototype_issues#36]
Comments from Dr. Phil Bourne

Clicking on the biocaddie logo on top left does not take you home as is customary.

**Comment by ianfore** [comment]
I would suggest we enter these as separate issues. That will make follow up easier.

#3 is a broad strategic issue.

**Comment by RuilingLiu** [comment]
Clicking on the DataMed logo takes you home, while clicking on the bioCADDIE logo takes you to bioCADDIE homepage
