### ISSUE TITLE
datamed.org contact not working due to captcha error

### ISSUE THREAD

**Issue by leebrian** [biocaddie/prototype_issues#366]
Hello there, I tried [submitting a registry](https://datamed.org/submit_repository.php) and using the [contact form](https://datamed.org/feedback.php) and they are both non functional for me as the captcha image fails to load, so I always get an error...
![image](https://user-images.githubusercontent.com/307968/75046449-16f06380-5493-11ea-9720-254dc9418c29.png)

Would you please send me an email address so I can submit via email?

This project seems not active but this is the only working method I could see described on dataned for contacting you all. 🤞

**Comment by ftiryaki** [comment]
Hi Brian,

Thank you for your feedback, we will be looking into this error.

Meanwhile can you please send an e-mail to me :  firat.tiryaki @ uth.tmc.edu  and I can help you directly.

Thanks

Firat

**Comment by ftiryaki** [comment]
Hi Brian,

This error is fixed, you can try again, or you can directly send message to my e-mail address.

Thanks

Firat
