### ISSUE TITLE
Links to related datasets?

### ISSUE THREAD

**Issue by readkev** [biocaddie/prototype_issues#39]
When looking at a specific dataset, it does not provide any links to related datasets I might find useful. Instead, it provides links to related publications. 

Example: Looking at the VAERS dataset for adverse events, I would hope to see a link to other related datasets on the reporting of adverse events suggested to me.

**Comment by chung88** [comment]
A relationship network graph would be nice, right now, I see a tag.  

Related Dataset:    hdl:3
Dataset ID :    hdl:1902.1/15463

**Comment by RuilingLiu** [comment]
@readkev In version 0.5, the "similar datasets" function has only been implemented for data sets in PDB, GEMMA and LINCS repositories. So not every data set has similar data sets.
