### ISSUE TITLE
Organism field shows strain only

### ISSUE THREAD

**Issue by ianfore** [biocaddie/prototype_issues#4]
**Steps taken**
Search for Varenicline in the datamed.biocaddie.org interface.

**Results**
One result is obtained. The organism is listed as SF9. 

**Expected results**
The organism species should be shown. PDB itself indicates that the species is Aplysia californica. 

** Further investigation **
It seems this is a product of the pipeline - the species is not visible in the elasticsearch record either.

**Comment by jgrethe** [comment]
Will check the metadata transformation for this as it appears in the PDB XML:

<PDBx:entity_src_genCategory>
      <PDBx:entity_src_gen entity_id="1">
         <PDBx:gene_src_common_name>CALIFORNIA SEA HARE</PDBx:gene_src_common_name>
         <PDBx:host_org_common_name>FALL ARMYWORM</PDBx:host_org_common_name>
         <PDBx:pdbx_gene_src_ncbi_taxonomy_id>6500</PDBx:pdbx_gene_src_ncbi_taxonomy_id>
         <PDBx:pdbx_gene_src_scientific_name>APLYSIA CALIFORNICA</PDBx:pdbx_gene_src_scientific_name>
         <PDBx:pdbx_host_org_ncbi_taxonomy_id>7108</PDBx:pdbx_host_org_ncbi_taxonomy_id>
         <PDBx:pdbx_host_org_scientific_name>SPODOPTERA FRUGIPERDA</PDBx:pdbx_host_org_scientific_name>
         <PDBx:pdbx_host_org_strain>SF9</PDBx:pdbx_host_org_strain>
         <PDBx:pdbx_host_org_vector_type>BACULOVIRUS</PDBx:pdbx_host_org_vector_type>
         <PDBx:plasmid_name>PFASTBAC</PDBx:plasmid_name>
      </PDBx:entity_src_gen>
   </PDBx:entity_src_genCategory>

**Comment by jgrethe** [comment]
I think this was resolved with prior updates to the pipeline.  See result below:

![sf9](https://cloud.githubusercontent.com/assets/1634917/15162171/703bdb8c-16b6-11e6-84bd-ab0864cbb626.jpg)
