### ISSUE TITLE
LINCS: Synonyms of "lincs"

### ISSUE THREAD

**Issue by chung88** [biocaddie/prototype_issues#40]
Not really a Life Science synonym.

Synonyms of "lincs"
Lincolnshire (geographic location)
http://datamed.biocaddie.org/expanded-query.php

**Comment by RuilingLiu** [comment]
"Lincolnshire" is not a synonym of "lincs". We will check our terminology server and correct this error.
Thank you!

**Comment by soysal** [comment]
Actually Lincs is also an abbreviation for Lincolnshire and it comes from [SNOMED CT concept id 223889007](http://browser.ihtsdotools.org/?perspective=full&conceptId1=223889007&edition=en-edition&release=v20160131&server=http://browser.ihtsdotools.org/api/snomed&langRefset=900000000000509007)
