### ISSUE TITLE
LINCS:  Search term "LINCS"

### ISSUE THREAD

**Issue by chung88** [biocaddie/prototype_issues#41]
Steps:
1.-  Type term "LINCS"
2.-  Suggest shows random numbers (slide 1, 2)
3.-  Take a screenshot, 18 shows in between "(18)"  (slide 3)

[bioCaddie-LINCS.pptx](https://github.com/biocaddie/prototype_issues/files/172237/bioCaddie-LINCS.pptx)

**Comment by chung88** [comment]
Steps:
1.-  Type term "Kinomescan"
2.-  Returns under Repositories LINCS (158)

The count for search term "LINCS" is not correct.

**Comment by RuilingLiu** [comment]
The suggestion function is a keyup event. It occurs when a keyboard key is released.

Each time you enter a letter, the backend program queries the current string. The number in slide 1 might be the result of the string "LI", the number in slide 2 might be the result of string "LINC". And the number in slide 3 is the result of the string "LINCS".

**Comment by chung88** [comment]
The suggest is against the dataset tittle.  If the tittle does not have the term LINCS.  How can I list all the datasets from LINCS?

**Comment by RuilingLiu** [comment]
We don't have the option to list all the datasets from LINCS in the version 0.5. We will implement this function later. 

Thank you for your suggestion!

**Comment by RuilingLiu** [comment]
There are two options to view all data sets from LINCS.

**Option 1:**
1. One the landing page, click on search button without entering any keywords.
2. On the search result page, click on checkbox next to "LINCS" label to view all data sets from LINCS

![biocaddie data discovery index 2016-04-20 09-58-56](https://cloud.githubusercontent.com/assets/11318005/14679213/87758646-06de-11e6-92ca-a7401f3ca176.png)

**Option 2:**
1. Click on "23 Repositoties" link on the landing page

![biocaddie data discovery index 2016-04-20 10-00-53](https://cloud.githubusercontent.com/assets/11318005/14679292/cc9de2f4-06de-11e6-9e7f-bb2debb74058.png)

2 . Click on "LINCS" on the repository list page

![biocaddie data discovery index 2016-04-20 10-01-26](https://cloud.githubusercontent.com/assets/11318005/14679304/e146676c-06de-11e6-9bb8-9476a57b07fb.png)
