### ISSUE TITLE
Ranking Mechanism in Public Release

### ISSUE THREAD

**Issue by saeid-p** [biocaddie/prototype_issues#47]
This issue has been reported by Greg Farber.

This issue is very significant. How will the results be ranked once the infrastructure is open to the public?

**Comment by saeid-p** [comment]
Answered by @RuilingLiu
Hi Greg,

Thank you so much for your feedback!

How will the results be ranked once the infrastructure is open to the public?
In our current version, the results are ranked using Elasticsearch's default ranking algorithm. In our future release, we will track the users' selections and refine the ranking results based on their selections.

**Comment by sthagstrom** [comment]
Testing reply to see where it goes.

**Comment by aegururaj** [comment]
The thread was opened during testing.
