### ISSUE TITLE
Issue With Landing Page Search Box

### ISSUE THREAD

**Issue by saeid-p** [biocaddie/prototype_issues#49]
This issue has been reported by Andrew Su.

The front page search box doesn't quite work as I'd expect. you do live searches as people type, but they apparently are restricted to whole words. For example, when I am typing "melano" I see zero hits, but I am expecting to see the totals for "melanoma" + "melanocyte" (plus other terms starting with "melano").

**Comment by soysal** [comment]
Even if the prefix "melano" seems very specific, a partial search will include many different terms like melanol, melanoblastoma, melanotic ... (e.g. stool, macule, ...), melanocytosis, melanopa (Cheilosia, Dolichogenidea, ...), melanoblast, melanotan, melanosis, melanoblastosis, melanocytoma, ... and the result set will be  a jam of unrelated terms. In turn it's very less likely to be useful for search purposes. On the other hand, especially if the user is searching for shorter terms like "MEL", this behavior will bring too many noises, and make this utility practically useless.
If you have any real life use case, which requires this functionality, please reopen this issue with your example.
