### ISSUE TITLE
Problems reported using the Google Chrome Web Browser

### ISSUE THREAD

**Issue by ianfore** [biocaddie/prototype_issues#5]
This was reported via email but no further details were available.

**Comment by ianfore** [comment]
The following steps were performed in an attempt to investigate.
Installed Chrome on Mac 
Went to datamed.biocaddie.org 
Was prompted for user name and password in a dialog box. 

provided biocaddie/biocaddie in response 
Successfully logged in 
Entered "breast cancer" - one of the example searches given. 
Got results back. 
I am not investigating here whether they are the right results, it would not be expected that the browser being used would be a factor here.
This test seems to confirm that basic functionality seems to be working in Chrome. 
![chrome prompt](https://cloud.githubusercontent.com/assets/4731517/9888839/40f6dd42-5bc5-11e5-93ea-6bf9e25c8a97.jpg)

**Comment by ianfore** [comment]
From: "Lin, Dawei (NIH/NIAID) [E]" <dawei.lin@nih.gov>
Date: Monday, September 14, 2015 at 11:36 AM
Hi All,
First of all, I am a Chrome user on Mac. I did not find any big problems . The popup window at the login seems to me is by design to restrict access for earlier testers. It may go away when it is released to the public. 
...
Thank you,
Dawei

**Comment by ianfore** [comment]
With the additional data point provided by Dawei I suggest we conclude that no issue with Chrome itself has been identified. So the following actions are proposed. Pending these we can close this issue.
1. Sufficient support should provided to anyone who is directed to use the prototype. This may be via documentation or otherwise.
2. The project team should make a reasonable statement about what web browsers it can support.
   Note that the browser testing done in evaluating this issue is limited. Browser specific issues may be uncovered with Chrome, or any other browser, as more detailed testing is performed in bioCADDIE. That will be addressed as and when it occurs. #2 above was added to provide for some limitation of the scope of that.

**Comment by RuilingLiu** [comment]
We have checked the cross-browser compatibility of the website by testing multiple browsers on multiple platforms. The website supports the following browsers:
1. Chrome
2. Firefox
3. Safari
4. Internet Explorer

The browsers we used for testing are: Internet Explorer 11, Safari version 8.0.8, FireFox version 40.0.3 and Chrome version 45.

**Comment by ianfore** [comment]
Thank you. With constantly changing browser versions this is always hard to stay on top of. The difficulty is understood. Aside from that, the four browsers named seem good to go with.
