### ISSUE TITLE
Linking LINCS datasets to LINCS portal

### ISSUE THREAD

**Issue by saeid-p** [biocaddie/prototype_issues#53]
This issue has been reported by Stephan Schurer.

Can you link LINCS datasets to the LINCS Portal. Via datasets IDs. http://lincsportal.ccs.miami.edu/datasets/ This is available via our APIs. 

Thanks, Stephan

**Comment by naturalbeau** [comment]
Link the LINCS dataset to the LINCS Portal in the display-item page.
