### ISSUE TITLE
"Contact" feature without GitHub account

### ISSUE THREAD

**Issue by saeid-p** [biocaddie/prototype_issues#54]
This issue has been reported by Lucila Ohno-Machado.

For those who do not want to set up an account in GitHub there this "contact me" page could be linked from the feedback solicitation box that appears in the left column after filtering options. The dropdown "feedback" tab should also include a link to this "contact me" page. I believe we should allow for anonymous feedback as well. Wherever people are asked to provide name and email address there should be a link to a privacy policy indicating that these will not be sold, etc.

**Comment by RuilingLiu** [comment]
There is a link to "contact me" page under the "feedback" tab. Users can reach this link by clicking on "Feedback" tab, then clicking on "Report an issue" label

<img width="503" alt="screen shot 2016-03-23 at 9 38 04 am" src="https://cloud.githubusercontent.com/assets/11318005/13998361/d3583bd4-f104-11e5-9f7a-dc3acab86486.png">

**Comment by RuilingLiu** [comment]
Privacy policy has been added. It is highlighted in red

![screen shot 2016-04-04 at 3 01 42 pm](https://cloud.githubusercontent.com/assets/11318005/14261438/324b6484-fa76-11e5-836d-3e7241f7c8e8.png)
