### ISSUE TITLE
Retrieving synonyms while cookies disabled

### ISSUE THREAD

**Issue by saeid-p** [biocaddie/prototype_issues#55]
This issue has been reported by Lucila Ohno-Machado.

One thing that I noticed is that if you disable cookies in Firefox 44.0.2 and in Safari 9.0.3 you can't get the synonyms. I attached a screenshot of what you get when cookies are disabled.

![screen shot 2016-03-18 at 11 59 43 am](https://cloud.githubusercontent.com/assets/6471104/13920838/f8cb28ae-ef42-11e5-94e0-5668aa5b6c19.png)

**Comment by RuilingLiu** [comment]
This issue has been fixed. 
Synonyms can be retrieved when cookies are disabled
