### ISSUE TITLE
Question about indexes linkage to control vocabularies

### ISSUE THREAD

**Issue by saeid-p** [biocaddie/prototype_issues#56]
This question has been reported by Stephan Schurer.

I had one question regarding the index. Are they linked to actual controlled vocabulary at the source repositories. I see different results for EGFR and Epidermal growth factor receptor and couple other examples. Or are they right now indexed to free text at at the source.
Looks though you do have a dictionary in bioCADDIE.
For LINCS we can demonstrate a real metadata-based integration; i.e. we know exactly what category any term is (disease, protein, assay, biological process, etc).

Stephan

**Comment by jgrethe** [comment]
This is part of the discussion the CDT is having with the LINCS group
