### ISSUE TITLE
Link to datasets using DOI

### ISSUE THREAD

**Issue by nursatranscriptomine** [biocaddie/prototype_issues#59]
For repositories that map datasets to DOIs, outbound links from DataMed to the repository datasets should be DOI-driven rather than URL driven - in the attached example, the link should be:

http://dx.doi.org/10.1621/zFZm9NEsnh

This resolves to the dataset page.

![datamed](https://cloud.githubusercontent.com/assets/14809879/14087973/5c2f041a-f4f2-11e5-90dd-1d74109c9a4d.png)

**Comment by naturalbeau** [comment]
In the prototype, only the Dryad and Nursa map datasets to DOIs. Now both of them are using DOI as the outbound links.
![4](https://cloud.githubusercontent.com/assets/6586013/14366621/5292432e-fcd9-11e5-9998-c330a95a91d0.png)
![3](https://cloud.githubusercontent.com/assets/6586013/14366623/54e50756-fcd9-11e5-85ba-287e10be8a22.png)

**Comment by nursatranscriptomine** [comment]
Thanks!
