### ISSUE TITLE
Error when searching without a keyword

### ISSUE THREAD

**Issue by agbeltran** [biocaddie/prototype_issues#6]
When pressing 'Go!' without a keyword, several coding errors appear in the website while it should report the lack of keyword or better, show all the available datasets. See screenshot.
<img width="1363" alt="screen shot 2015-09-29 at 19 53 46" src="https://cloud.githubusercontent.com/assets/1417033/10174885/ed00025c-66e3-11e5-95a8-9070534b1464.png">

**Comment by RuilingLiu** [comment]
Fix: #6

Thanks!
