### ISSUE TITLE
Add Breadcrumbs For Selected Fitlers

### ISSUE THREAD

**Issue by saeid-p** [biocaddie/prototype_issues#61]
A feedback from Jessie Tenenbaum.

Looks great overall! a few minor things. Would be nice to have "breadcrumbs" of what's been selected across the top with an X to easily remove any given filter.

**Comment by RuilingLiu** [comment]
"Breadcrumb" feature has been implemented

<img width="692" alt="screen shot 2016-04-22 at 12 02 48 pm" src="https://cloud.githubusercontent.com/assets/11318005/14748941/334381cc-0882-11e6-9a1d-930a05e2e43f.png">
