### ISSUE TITLE
Implement Access Controls and Audit Policy

### ISSUE THREAD

**Issue by saeid-p** [biocaddie/prototype_issues#64]
This feedback has been collected from survey feedback questionnaire form. In order to protect user's privacy, the personal information has been removed.

Access controls are critical. Every access needs to be authenticated. Every operation needs to be authorized. Policies are critical. You need to be able to enforce assertions about the system (presence of required access controls, presence of required metadata). You need to be able to automate tasks. Provability is critical. You need to be able to prove compliance with your policy assertions. Again note that data grids such as iRODS implement the above capabilities.

**Comment by jgrethe** [comment]
Not sure why access controls are critical as we are currently not searching over protected information.  

This comes from the iRODS group at RENCI.  Not sure why we would need provability of transactions as we are just a search site.

**Comment by jgrethe** [comment]
Am closing this as bioCADDIE is not a repository or data access infrastructure (like iRODS). One does not need to authenticate to PubMed or Google - however, once you are taken to the appropriate endpoint authentication maybe necessary. These access metadata have been developed by bioCADDIE Working Group 7: Accessibility Metadata for Datasets (https://biocaddie.org/group/working-group/working-group-7-accessibility-metadata-datasets)
