### ISSUE TITLE
Extending the range of metadata for datasets

### ISSUE THREAD

**Issue by saeid-p** [biocaddie/prototype_issues#65]
This feedback has been collected from survey feedback questionnaire form. In order to protect user's privacy, the personal information has been removed.

I see lack of metadata about each dataset -- especially in terms of description, what it is/has been used for, standards used, who created it, etc.

**Comment by jgrethe** [comment]
There is an on-going review of the metadata provided by the repositories.  Agree that we could add information on standards (e.g. what standard was used to supply the metadata).

**Comment by jgrethe** [comment]
Assigning to Anu as we are currently collecting information about standards used, etc...

**Comment by tjohnson250** [comment]
We need to put "Expanded Metadata" into a single issue. Yes, it is a usability issue, but given the lack of metadata in some of our data sources, I'm not sure what we can do at this point to address it.

**Comment by NinaSalimi** [comment]
We notified the sender of the feedback that we are working on this part and will update her once the process is completed.
