### ISSUE TITLE
Highlight the Search Terms

### ISSUE THREAD

**Issue by saeid-p** [biocaddie/prototype_issues#68]
This feedback has been collected from biocaddie Contact Us Form. In order to protect user's privacy, the personal information has been removed.

Thank you for the invitation to preview the DataMed prototype. Here are some initial comments I have after clicking around the DataMed site. So far, I’ve restricted my searches to the data I am most familiar with, NCBI GEO and BioProject. General comments: I like the overall interface styling, clean and modern. It would help to highlight the search terms in the retrievals.

**Comment by RuilingLiu** [comment]
This is the same request as #21 . @naturalbeau is working on #21 .
