### ISSUE TITLE
Make External Repositories Link More Obvious

### ISSUE THREAD

**Issue by saeid-p** [biocaddie/prototype_issues#69]
This feedback has been collected from biocaddie Contact Us Form. In order to protect user's privacy, the personal information has been removed.

On the full records, I think the button that links to the original record should be more obvious. This is particularly important if biocaddie indexing is not on the same schedule as the source database, which may lead to biocaddie not reflecting recent updates. 

In some cases, the link to the original record is not precise and may lead to confusion. For example the link from PRJNA126719 leads to a text search of the project title in BioProject, which retrieves 2 BioProjects, one of which is not relevant. GEO-specific comments:

**Comment by naturalbeau** [comment]
The external repositories link icon is changed to be the repository icon. Also the title will be different color and underline when mouse hover over it. The BioProject external link bug has been fixed.
![6](https://cloud.githubusercontent.com/assets/6586013/14533029/f63174b0-0228-11e6-8a91-248f7a9e1d0c.png)
