### ISSUE TITLE
Remove 'Home' button from homepage?

### ISSUE THREAD

**Issue by agbeltran** [biocaddie/prototype_issues#7]
Currently the home page contains a 'Home' button that refers to the same page.
I think it is unnecessary in the home page and suggest it is removed.

On the other hand, it is indeed useful  on the search results page to go back to the homepage.

**Comment by RuilingLiu** [comment]
"Home" button will be removed from the bioCADDIE prototype version 0.2.
Thanks!

Fix: #7
