### ISSUE TITLE
Ability to view results in different formats

### ISSUE THREAD

**Issue by saeid-p** [biocaddie/prototype_issues#71]
This feedback has been collected from survey feedback questionnaire form. In order to protect user's privacy, the personal information has been removed.

It would be great if we could get information on how to gain access to the datasets (e.g. license, required steps to gain access) and had the ability to view results in different formats (e.g. full description view, vs. snippet view).

**Comment by NinaSalimi** [comment]
An email was sent to the reporter of this issue indicating that these functions have been implemented in the latest version of the website.
