### ISSUE TITLE
Having a feature to build collections and have more filters.

### ISSUE THREAD

**Issue by saeid-p** [biocaddie/prototype_issues#73]
This feedback has been collected from survey feedback questionnaire form. In order to protect user's privacy, the personal information has been removed.

It is valuable if we could have a "MyNCBI" type tool where I can build collections. I'm glad to see saved searches is already included. Additional filters for limiting to "human, animal, cell line, etc.", limiting to a publication date range is useful too.

**Comment by RuilingLiu** [comment]
The function to build collections has been implemented
