### ISSUE TITLE
Feedback About Search Page

### ISSUE THREAD

**Issue by saeid-p** [biocaddie/prototype_issues#74]
This feedback has been collected from survey feedback questionnaire form. In order to protect user's privacy, the personal information has been removed.
- The repositories page made me think that when I clicked on it it would take me to all datasets from that repository, not directly to the repository webpage.
- I am confused by the synonyms tag -- what does this mean? For example, when I searched "Canada" a synonym included was "Ginger, Wild" -- are these supposed to be like MeSH terms?
- Please provide metadata on the specific publications that are either "generated from" a specific dataset OR the publication that the dataset is a "product of".

**Comment by RuilingLiu** [comment]
"The repositories page made me think that when I clicked on it it would take me to all datasets from that repository, not directly to the repository webpage."

#41

**Comment by tjohnson250** [comment]
Seems like three issues, lets separate them and discuss.

**Comment by NinaSalimi** [comment]
They are separated now.
The second question has been moved to issue #141 
The third question has been moved to issue #142

**Comment by naturalbeau** [comment]
The first question is fixed. In repositories page, when user clicks on the repository name, it  would go to the page showing all datasets from that repository.

**Comment by naturalbeau** [comment]
Response has been sent back to the user and no further reply. I will close the issue.
