### ISSUE TITLE
Expand/Collapse and Navigation Issue

### ISSUE THREAD

**Issue by saeid-p** [biocaddie/prototype_issues#76]
This feedback has been collected from survey feedback questionnaire form. In order to protect user's privacy, the personal information has been removed.

On the main page, there are some 'drop down' icons (arrows) that do not have any capacity to minimize/maximize. Similarly, when navigated to an entry (example: http://datamed.biocaddie.org/display-item.php?repository=0009&idName=Dataset.briefTitle&id=e005c7f0-1bc6-4a49-8f56-306137141cca&query=cancer), opening or closing the dropdowns treats this as a new page each time when trying to navigate back (using the back button of the browser rather than the small button on the page). Meaning if I minimize 'study', 'treatment', and 'other' I must press back 4 times before reaching my search results again.

**Comment by RuilingLiu** [comment]
Thank you for your feedback!

The "drop down" icons that do not have any capacity to minimize/maximize have been removed.
Opening or closing the dropdowns treats this as a new page, so the small button on the page ("<") is a better option than the back button of the broswer.
