### ISSUE TITLE
Export citations to clipboard directly

### ISSUE THREAD

**Issue by saeid-p** [biocaddie/prototype_issues#77]
This feedback has been collected from survey feedback questionnaire form. In order to protect user's privacy, the personal information has been removed.

It would be great to have a citation function that allows you to copy the citation for the dataset to your clipboard.

**Comment by SciMeg** [comment]
I second this! But question is, are you copying the citation to (1) the dataset, or (2) the data entity? e.g., PDB has distinct attribution guidelines dependent on citing the PDB itself, or the individual PDB entry.

**Comment by saeid-p** [comment]
This feature has been implemented and will be available with the version 1 release.
I will close this enhancement ticket. If further suggestion was needed, we can create a new issue in that regard.
