### ISSUE TITLE
Indexing data papers

### ISSUE THREAD

**Issue by saeid-p** [biocaddie/prototype_issues#78]
This feedback has been collected from survey feedback questionnaire form. In order to protect user's privacy, the personal information has been removed.

From a publishers perspective, I would be interested in the potential of indexing data papers in DDI as well as receiving data paper submissions from DDI.

**Comment by jgrethe** [comment]
We are testing this with Nature Scientific Data currently.  I am not sure about receiving data paper submissions from the DDI.  As we don't archive data sets (i.e. bioCADDIE is not a data repository) we wouldn't be submitting data papers.

**Comment by saeid-p** [comment]
@aegururaj Do you want to keep this issue open for future release? And do you want Nina to contact the participant about Jeff's response?

**Comment by NinaSalimi** [comment]
We are testing this with Nature Scientific Data currently. We are not sure about receiving data paper submissions from the DDI. As we don't archive data sets (i.e. bioCADDIE is not a data repository) we wouldn't be submitting data papers.

**Comment by NinaSalimi** [comment]
Also, an email was sent to the reporter of this issue...
