### ISSUE TITLE
Error "Undefined offset: 0 in /var/www/biocaddie/single_item.php on line 26"

### ISSUE THREAD

**Issue by agbeltran** [biocaddie/prototype_issues#8]
To reproduce:
1. search for 'software'
2. go to the last page of results, pressing 'Last' 
3. click on the title of results number 37
4. error appears at the top of the record page, as follows
"Notice: Undefined offset: 0 in /var/www/biocaddie/single_item.php on line 26"
See screenshots.

<img width="1094" alt="screen shot 2015-09-29 at 20 08 47" src="https://cloud.githubusercontent.com/assets/1417033/10175297/035351ce-66e6-11e5-9db0-f4fec8314842.png">
<img width="1343" alt="screen shot 2015-09-29 at 20 06 43" src="https://cloud.githubusercontent.com/assets/1417033/10175366/4e22b17c-66e6-11e5-80ae-6308cefc1b44.png">

**Comment by RuilingLiu** [comment]
Fix: #8

Thanks!
