### ISSUE TITLE
Display issue: not obvious one should go "Home" to access the search engine

### ISSUE THREAD

**Issue by margolisr** [biocaddie/prototype_issues#81]

**Comment by RuilingLiu** [comment]
Hi,

We have a search panel on every page, so a user doesn't have to go "Home" to access the search engine.

![biocaddie data discovery index 2016-04-14 13-15-11](https://cloud.githubusercontent.com/assets/11318005/14538767/f4e29890-0242-11e6-8bff-98d12353b0ba.png)

**Comment by margolisr** [comment]
I’m just wondering about how the ‘naïve’ user would fare? For some there may be a need to be almost force-fed navigation and if they must hunt around for a clear entry to the home page they may just give up.

**Comment by RuilingLiu** [comment]
Hi @margolisr 
Is the navigation bar good enough for user to find the home page? Should we close this issue?

**Comment by margolisr** [comment]
Yes. Thank you.

Sent from my iPad

On Sep 16, 2016, at 1:50 PM, RuilingLiu <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi @margolisrhttps://github.com/margolisr
Is the navigation bar good enough for user to find the home page? Should we close this issue?
