### ISSUE TITLE
Consider automatically creating GitHub entry for issues entered via the feedback form

### ISSUE THREAD

**Issue by ianfore** [biocaddie/prototype_issues#83]
GitHub has an API that would allow an issue to be created in GitHub. How difficult would it be to call that API when a user submits the feedback form? 
This would kick start the process of managing issues raised through the form.
Could this capture user contact information if the user chose to to add it?

**Comment by RuilingLiu** [comment]
Hi Ian,

I tested the [PHP GitHub API](https://github.com/KnpLabs/php-github-api). It is not hard to call the API and post an issue when a user submits the feedback form.

But a user may submit multiple issues in one feedback form. And this API cannot split the issues in the form automatically. How should we handle this condition?

**Comment by RuilingLiu** [comment]
This feature has been implemented.
