### ISSUE TITLE
Functions (like faceted filter capability) not working in internet explorer

### ISSUE THREAD

**Issue by dianneusa** [biocaddie/prototype_issues#85]
![snip ie v firefox faceted search](https://cloud.githubusercontent.com/assets/6653798/14821551/2819a906-0b99-11e6-9cba-045f30416047.jpg)

**Comment by RuilingLiu** [comment]
Hi,

Could you please send me the version number of this Internet Explorer? I cannot reproduce this bug using Internet Explorer 11.

**Comment by dianneusa** [comment]
Sure, here is a snap:
[cid:image001.png@01D1A0A4.8ABBF6F0]

**Comment by RuilingLiu** [comment]
Hi,

It seems that the screenshot was not attached successfully.

**Comment by dianneusa** [comment]
![ie version](https://cloud.githubusercontent.com/assets/6653798/14868017/670e6a42-0c99-11e6-98c5-60c3eed62d44.jpg)

**Comment by RuilingLiu** [comment]
Bug cannot be reproduced using the same internet explorer version.

**Comment by RuilingLiu** [comment]
Hi @dianneusa ,

Do you still have the same issue?

**Comment by dianneusa** [comment]
Still not seeing check boxes in IE…here’s a snap:
[cid:image001.jpg@01D1C18C.026216A0]

**Comment by RuilingLiu** [comment]
Which operating system are you using?

**Comment by dianneusa** [comment]
The latest Windows version; I'm an HHS employee so whatever is approved for all staff is what I use.

Sent from my iPhone

On Jun 8, 2016, at 1:48 PM, RuilingLiu <notifications@github.com<mailto:notifications@github.com>> wrote:

Which operating system are you using?

**Comment by RuilingLiu** [comment]
Hi @dianneusa ,

We tested this issue using Internet Explore 11 on both Window 7 and Window 10 machine. But we cannot reproduce the bug. So we will close this issue for now.
