### ISSUE TITLE
Need transparency on synonyms to explain different query results 

### ISSUE THREAD

**Issue by SciMeg** [biocaddie/prototype_issues#87]
When I search "Akt" and filter for the PDB repository, I get 145 results. In the PDB itself, there are 93 results for the query. I can see the synonyms list next to results in DataMed, but it isn't clear to me which of those synonyms are inclusive of what is coming back in the PDB.

**Comment by naturalbeau** [comment]
The search strategy used in datamed is different from PDB website. That is the reason why we get different results. The "Akt" has five synonyms. In Datamed, we search the "Akt" as well as its synonyms. In the result, we have highlighted the matched term(the matched "Akt" and its synonyms have been highlighted). 
![9](https://cloud.githubusercontent.com/assets/6586013/14919362/1414c09c-0dee-11e6-86d0-0c77fa5afaf5.png)

**Comment by SciMeg** [comment]
Thanks, I understand what is happening, but my comment is on the user experience - there should be something to make that clear to the user.
For example, instead of _Displaying 10 of 145 results for "Akt"_, you could add _and its synonyms_. 
AND/OR
Have a "help" or "info" icon next to that or the Synonyms list on the right and provide a tooltip that explains that DataMed gives more than the PDB.

Adding synonyms means that DataMed enhances search capabilitities beyond the PDB itself --- that's a great value-add for this product, and it should be highlighted!

**Comment by naturalbeau** [comment]
Thanks for the feedback. We have changed the "Search Details" on the right column. It shows how we construct the query. When a query has synonyms, the synonyms are connected using OR in our search.
![3](https://cloud.githubusercontent.com/assets/6586013/14990047/6a8cb5e4-1120-11e6-97ef-46b307495842.png)
