### ISSUE TITLE
links from repository list lead to unable to connect error

### ISSUE THREAD

**Issue by dianneusa** [biocaddie/prototype_issues#88]
on the http://datamed.biocaddie.org/repository_list.php page, click on any link get "Unable to connect" msg--looks like a local host problem. see image snap
![repos list link error](https://cloud.githubusercontent.com/assets/6653798/14867911/ed1fd018-0c98-11e6-9eb8-4d4be46f5ceb.jpg)

**Comment by RuilingLiu** [comment]
Thank you for your feedback! This bug has been fixed.
