### ISSUE TITLE
Change order of facets?

### ISSUE THREAD

**Issue by agbeltran** [biocaddie/prototype_issues#9]
In the search results, when looking at the overall results (e.g. Step 1 - search for 'cell line' and consider the page with the search results), the facets appear in the order:
- data types (Show results for: protein, etc)
- repositories

In the page for the results within a repository (Step 2- in the previous results page, select 'RCBS Protein Data Bank') the facets appear as:
- repositories
- Refined by: 
  - keywords, etc

For consistency, I think it would be better to show always the repositories as the first facet. Thus, in the result page after Step 1, put the repositories first.

See screenshots.

<img width="1260" alt="screen shot 2015-09-29 at 21 47 30" src="https://cloud.githubusercontent.com/assets/1417033/10177847/4ce18a3c-66f4-11e5-8b5e-9d7220d99f5e.png">
<img width="1241" alt="screen shot 2015-09-29 at 21 47 39" src="https://cloud.githubusercontent.com/assets/1417033/10177849/4f27ff74-66f4-11e5-9833-28c4d31ff9bc.png">

**Comment by RuilingLiu** [comment]
Thank you for your suggestion! 
We are working on the new interface and the repository facet will be the first facet on all pages.

Fix:#9
