### ISSUE TITLE
datamed numbers differ from databases

### ISSUE THREAD

**Issue by dianneusa** [biocaddie/prototype_issues#93]
I'm confused about results...

CT.gov has 214,105 studies. Datamed: Displaying 192501 results for "ClinicalTrials". 
Entrez Bioproject: all[sb]: Items: 1 to 20 of 174826. Datamed: Displaying 155851 results for "BioProject"

Is an API pulling the data from these databases?

**Comment by jgrethe** [comment]
Yes, we do pull the data from a repository's API or download.  However, for the prototype, we only crawl the repositories at certain times (e.g. around releases) - so the index can end-up having different total counts (e.g. ClinicalTrials.gov is now at 215,060 studies).
