### ISSUE TITLE
Issue with DataMed advanced search

### ISSUE THREAD

**Issue by saeid-p** [biocaddie/prototype_issues#94]
This issue was submitted by Lucila Machado.

The attached search generated an odd synonym and >38k hits, so there must be something wrong with the advanced search.

<img width="1022" alt="screen shot 2016-05-02 at 5 58 30 pm" src="https://cloud.githubusercontent.com/assets/6471104/14986810/fd16e244-1112-11e6-8696-833041f720a5.png">

**Comment by naturalbeau** [comment]
The bug has been fixed. FYI, in advanced search, we do not use synonyms expansion to search.
![2](https://cloud.githubusercontent.com/assets/6586013/14989124/ee3530d8-111b-11e6-8393-c8d2f8d2a84b.png)
