### ISSUE TITLE
Invalid results for queries with special characters

### ISSUE THREAD

**Issue by saeid-p** [biocaddie/prototype_issues#95]
I tried to search the following term, but the results are invalid and if you select specific repository, it doesn't show any relevant result.

**_Bacterial 16S RRNA Genes Amplified From ND-Fed Mouse#2(TM003) Feces And Sequ_**

This is the link to reproduce the error:
http://datamed.biocaddie.org/search.php?query=Bacterial+16S+rRNA+genes+amplified+from+ND-fed+mouse%232%28TM003%29+feces+and+sequ&searchtype=data

And this is how I tried to filter the repository:
http://datamed.biocaddie.org/search.php?query=Bacterial%2016S%20rRNA%20genes%20amplified%20from%20ND-fed%20mouse#2(TM003) feces and sequ&searchtype=data&offset=1&repository=0009

**Comment by naturalbeau** [comment]
The bug has been fixed.  Search the "Bacterial 16S RRNA Genes Amplified From ND-Fed Mouse#2(TM003) Feces And Sequ" in datamed, there is no relevant result avaiable.
