### ISSUE TITLE
NURSA currently listed under "Unspecified", should be "Gene Expression"

### ISSUE THREAD

**Issue by nursatranscriptomine** [biocaddie/prototype_issues#96]
NURSA is currently listed under "Unspecified" in search result suggestions, should be "Gene Expression"

**Comment by naturalbeau** [comment]
NURSA has been changed to be under "Gene Expression".

**Comment by nursatranscriptomine** [comment]
NURSA is still appearing in the "Unspecified" Category on the "DATA TYPES" page

http://datamed.biocaddie.org/datatypes.php 

![biocaddie](https://cloud.githubusercontent.com/assets/14809879/15482884/a70907fc-20f7-11e6-96d0-52bcc68c9c86.png)

**Comment by naturalbeau** [comment]
Now it is been fixed.
![1](https://cloud.githubusercontent.com/assets/6586013/15484285/ec0661c2-20fe-11e6-8640-7306951f3a6f.png)
